/* JS */ gapi.loaded_0(function(_){var window=this;
try{
_.m=function(a){throw a;};_.q=void 0;_.s=!0;_.t=null;_.v=!1;_.aa=function(){return function(a){return a}};_.x=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.z=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.ea=function(a){return a!==_.q};_.fa=function(a){return"array"==(0,_.da)(a)};_.ga=function(a){var c=typeof a;return"object"==c&&a!=_.t||"function"==c};_.ha=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.ia=function(a,c,f){a||(0,_.m)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.D=function(a,c,f){_.D=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ha:_.ia;return _.D.apply(_.t,arguments)};
_.ja=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.E=function(a,c){function f(){}f.prototype=c.prototype;a.z=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.m)(a)};_.ka=_.ka||{};_.F=this;_.la="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.ma=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.D.apply(_.t,f)}return(0,_.D)(this,a)};
_.na=window.gapi||{};_.pa=window.gadgets||{};_.H=window.osapi=window.osapi||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.v},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.v},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.v},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.s,"pos.plusones.list":_.s,"pos.plusones.get":_.s,"chili.people.get":_.s,"pos.plusones.insert":_.s,"chili.activities.list":_.s,"pos.plusones.delete":_.s,"chili.activities.get":_.s,"chili.activities.search":_.s,"pos.plusones.getSignupState":_.s},
requestCache:{enabled:_.s},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.s},transport:{isProxyShared:_.s},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.v}}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{card:{url:":socialhost:/u/:session_index:/_/hovercard/card"}}});
}catch(e){_._DumpException(e)}
try{
_.I=function(a,c,f){a=a.split(".");f=f||_.F;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.ea)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};_.qa=function(a,c,f){return a[c]=a[c]||f};_.ra=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.sa=function(a){return(0,window.String)(a).replace(_.ta,"&amp;").replace(_.ua,"&lt;").replace(_.va,"&gt;").replace(_.wa,"&quot;").replace(_.xa,"&#39;")};
_.ya=function(){var a;if((a=window.Object.create)&&_.za.test(a))a=a(_.t);else{a={};for(var c in a)a[c]=_.q}return a};_.Aa=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Ba=function(a,c){var a=a||{},f;for(f in a)(0,_.Aa)(a,f)&&(c[f]=a[f])};_.Ca=function(a,c){a||(0,_.m)((0,window.Error)(c||""))};_.Da=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g"),c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};
_.Fa=function(a){var a=a.match(_.Ga),c=(0,_.ya)();c.lc=a[1];c.$a=a[3]?[a[3]]:[];c.Ue=a[5]?[a[5]]:[];return c};_.Ha=function(a){return a.lc+(0<a.$a.length?"?"+a.$a.join("&"):"")+(0<a.Ue.length?"#"+a.Ue.join("&"):"")};_.Ia=function(a){var c=[];if(a)for(var f in a)(0,_.Aa)(a,f)&&a[f]!=_.t&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};_.Ja=function(a,c,f){a=(0,_.Fa)(a);a.$a.push.apply(a.$a,(0,_.Ia)(c));a.Ue.push.apply(a.Ue,(0,_.Ia)(f));return(0,_.Ha)(a)};
_.Ka=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.La=function(a){return!_.Ma.dpo?(0,_.Da)(a,"jsh",_.Ma.h):_.Ma.h};_.Oa=function(a){return(0,_.Da)(a,"_bsh",_.Ma.bsh)};_.Pa=function(){return window.___jsl=window.___jsl||{}};_.Qa=function(a){var c=(0,_.Pa)();c[a]=c[a]||[];return c[a]};_.Ra=function(a){var c=(0,_.Pa)();c.cfg=!a&&c.cfg||{};return c.cfg};_.Sa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.Ta=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Sa)(a[f])&&!(0,_.Sa)(c[f])?(0,_.Ta)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Sa)(c[f])?[]:{},(0,_.Ta)(a[f],c[f])):a[f]=c[f])};
_.Ua=function(a){(0,_.Ra)(_.s);var c=window.___gcfg,f=(0,_.Qa)("cu");if(c&&c!==window.___gu){var g={};(0,_.Ta)(g,c);f.push(g);window.___gu=c}var c=(0,_.Qa)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[],n=(0,_.Pa)().u;n&&l.push(n);(0,_.Pa)().us&&l.push.apply(l,(0,_.Pa)().us);for(n=0;n<h.length;++n)for(var r=h[n],u=0;u<l.length;++u)r.src&&0==r.src.indexOf(l[u])&&g.push(r);0==g.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)if(!g[h].getAttribute("gapi_processed")){g[h].setAttribute("gapi_processed",
_.s);(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.q;if(l){for(;0==l.charCodeAt(l.length-1);)l=l.substring(0,l.length-1);n=_.q;try{n=(new window.Function("return ("+l+"\n)"))()}catch(w){}if("object"===typeof n)l=n;else{try{n=(new window.Function("return ({"+l+"\n})"))()}catch(y){}l="object"===typeof n?n:{}}}else l=_.q;l&&c.push(l)}a&&(g={},(0,_.Ta)(g,a),f.push(g));g=(0,_.Qa)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Ta)((0,_.Ra)(),g[a]);g=(0,_.Qa)("ci");
a=0;for(c=g.length;a<c;++a)(0,_.Ta)((0,_.Ra)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Ta)((0,_.Ra)(),f[a])};_.J=function(a,c){if(!a)return(0,_.Ra)();for(var f=a.split("/"),g=(0,_.Ra)(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.q?g:c};_.Va=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var r={},g=g[h[l]]=r;g[h[l]]=c}(0,_.Ua)(f)};
_.Wa=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.qa)(_.Ma,"ci",[]).push(a),window.__GOOGLEAPIS=_.q)};_.N=function(a,c){c="function"==typeof _.Xa&&(0,_.Xa)(a,c)||c;(0,_.I)(a,c,_.q)};
_.Ya=window;_.Za=window.document;_.za=/\[native code\]/;_.ta=/&/g;_.ua=/</g;_.va=/>/g;_.wa=/"/g;_.xa=/'/g;_.$a=(0,_.qa)(_.Ya,"gapi",{});_.Ga=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Ma=(0,_.qa)(_.Ya,"___jsl",(0,_.ya)());(0,_.qa)(_.Ma,"I",0);(0,_.qa)(_.Ma,"hel",10);_.Wa&&(0,_.Wa)();(0,_.Ua)();(0,_.N)("gapi.config.get",_.J);(0,_.N)("gapi.config.update",_.Va);
}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.gb={go:{},N:{}};_.hb={go:{},N:{}};
}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.P=_.P||{};
}catch(e){_._DumpException(e)}
try{
_.P=_.P||{};_.P.Cd=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.P.ye=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

}catch(e){_._DumpException(e)}
try{
_.pb=function(a,c){return window.String.fromCharCode(c)};_.P=_.P||{};_.qb={"0":_.v,10:_.s,13:_.s,34:_.s,39:_.s,60:_.s,62:_.s,92:_.s,8232:_.s,8233:_.s,65282:_.s,65287:_.s,65308:_.s,65310:_.s,65340:_.s};_.P.escape=function(a,c){if(a){if("string"===typeof a)return _.P.be(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.P.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.P.be(g)]=_.P.escape(a[g],_.s));return f}}return a}; _.P.be=function(a){if(!a)return a;for(var c=[],f,g,h=0,l=a.length;h<l;++h)f=a.charCodeAt(h),g=_.qb[f],g===_.s?c.push("&#",f,";"):g!==_.v&&c.push(a.charAt(h));return c.join("")};_.P.jr=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.pb)};

}catch(e){_._DumpException(e)}
try{
_.ub=_.ub||{};_.ub.Fn=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

}catch(e){_._DumpException(e)}
try{
_.vb=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.ub=_.ub||{};
_.ub.Eg=function(){var a=_.ub.Fn().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.t))?h.overflowY:_.t);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.t))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var l=h.offsetTop+h.offsetHeight+(0,_.vb)(h,"margin-bottom"),a=window.Math.max(a,l);c.push(h)}}return a+(0,_.vb)(window.document.body,"border-bottom")+(0,_.vb)(window.document.body,"margin-bottom")+(0,_.vb)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};

}catch(e){_._DumpException(e)}
try{
_.lb=function(a,c){if(!(a<_.mb)&&_._console$$inline_260)if(2===a&&_._console$$inline_260.warn)_._console$$inline_260.warn(c);else if(3===a&&_._console$$inline_260.error)try{_._console$$inline_260.error(c)}catch(f){}else _._console$$inline_260.log&&_._console$$inline_260.log(c)};_.nb=function(a){(0,_.lb)(1,a)};_.ob=function(a){(0,_.lb)(2,a)};_.fb=function(a){(0,_.lb)(3,a)};_.nb.INFO=1;_.nb.WARNING=2;_.nb.NONE=4;_.mb=1; _._console$$inline_260=window.console?window.console:window.opera?window.opera.postError:_.q;

}catch(e){_._DumpException(e)}
try{
_.P=_.P||{};_.P.Wd=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.ob)("cannot attachBrowserEvent: "+c)};_.P.fp=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.ob)("cannot removeBrowserEvent: "+c)};

}catch(e){_._DumpException(e)}
try{
_.xb=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;y=w=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;for(var a=h[0],g=h[1],l=h[2],r=h[3],u=h[4],y,w,f=0;80>f;f++)40>f?20>f?(y=r^g&(l^r),w=1518500249):(y=g^l^r,w=1859775393):60>f?(y=g&l|r&(g|l),w=2400959708):(y=g^l^r,w=3395469782),y=((a<<5|a>>>27)&4294967295)+
y+u+w+c[f]&4294967295,u=r,r=l,l=(g<<30|g>>>2)&4294967295,g=a,a=y;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+r&4294967295;h[4]=h[4]+u&4294967295}function f(a,f){if("string"===typeof a){for(var a=(0,window.unescape)((0,window.encodeURIComponent)(a)),g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==w)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,y+=64;for(;g<f;)if(l[w++]=a[g++],y++,64==w){w=0;for(c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,y+=64}}
function g(){var a=[],g=8*y;56>w?f(r,56-w):f(r,64-(w-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var u=24;0<=u;u-=8)a[g++]=h[n]>>u&255;return a}for(var h=[],l=[],n=[],r=[128],u=1;64>u;++u)r[u]=0;var w,y;a();return{reset:a,update:f,Lq:g,Qe:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

}catch(e){_._DumpException(e)}
try{
_.zb=function(a){var c=(0,_.xb)();c.update(a);return c.Qe()};_.Ab=window.crypto;
if(_.Ab&&"function"==typeof _.Ab.getRandomValues)_.yb=function(){var a=new window.Uint32Array(1);_.Ab.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.Bb=(0,_.J)("random/maxObserveMousemove");_.Bb==_.t&&(_.Bb=-1);_.Cb=0;_.Db=window.Math.random();_.Eb=1;_.Fb=1E6*(window.screen.width*window.screen.width+window.screen.height);_.Gb=function(a){var a=a||window.event,c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.Eb=_.Eb*c%_.Fb;0<_.Bb&&++_.Cb==_.Bb&&
_.P.fp(window,"mousemove",_.Gb,_.v)};0!=_.Bb&&_.P.Wd(window,"mousemove",_.Gb,_.v);_.Hb=(0,_.zb)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.Db);_.yb=function(){var a=_.Eb,a=a+(0,window.parseInt)(_.Hb.substr(0,20),16);_.Hb=(0,_.zb)(_.Hb);return a/(_.Fb+window.Math.pow(16,20))}};
(0,_.N)("shindig.random",_.yb);
}catch(e){_._DumpException(e)}
try{
_.P=_.P||{};_.Ib=[];_.P.Zq=function(a){_.Ib.push(a)};_.P.er=function(){for(var a=0,c=_.Ib.length;a<c;++a)_.Ib[a]()};
}catch(e){_._DumpException(e)}
try{
_.Lb=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.Lb&&(0,_.Va)((0,_.Lb)());_.Jb={L:function(a,c,f){f&&f((0,_.J)())},get:function(a){return(0,_.J)(a)},update:function(a,c){c&&(0,_.m)("Config replacement is not supported");(0,_.Va)(a)},aa:(0,_.x)()};
(0,_.N)("gadgets.config.register",_.Jb.L);(0,_.N)("gadgets.config.get",_.Jb.get);(0,_.N)("gadgets.config.init",_.Jb.aa);(0,_.N)("gadgets.config.update",_.Jb.update);
}catch(e){_._DumpException(e)}
try{
if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.jb=function(a){return this[a]};_.kb=/___$/;_.O={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.v}},stringify:function(a){function c(a){return f.call(this,a,_.jb)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.kb.test(a)?c:_.q})}catch(h){return _.t}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.O=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,l,n;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){n=a.length;for(l=0;l<n;l+=1)h.push(c(a[l])||"null");return"["+h.join(",")+"]"}for(l in a)!/___$/.test(l)&&a.hasOwnProperty(l)&&"string"===typeof l&&(n=c(a[l]))&&h.push(c(l)+":"+n);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.v}}}();
_.O.Fi=function(a){var c={};if(a===_.t||a===_.q)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.t===g||_.q===g||(c[f]="string"===typeof g?g:_.O.stringify(g))}return c};(0,_.N)("gadgets.json.flatten",_.O.Fi);(0,_.N)("gadgets.json.parse",_.O.parse);(0,_.N)("gadgets.json.stringify",_.O.stringify);(0,_.N)("gadgets.json.flatten",_.O.Fi);(0,_.N)("gadgets.json.parse",_.O.parse);(0,_.N)("gadgets.json.stringify",_.O.stringify);

}catch(e){_._DumpException(e)}
try{
_.P=_.P||{};_.rb=_.t;
_.P.$=function(a){var c="undefined"===typeof a;if(_.rb!==_.t&&c)return _.rb;for(var f={},a=a||window.document.location.href,g=a.indexOf("?"),h=a.indexOf("#"),a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&"),g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,l=a.length;h<l;++h){var n=a[h].indexOf("=");if(-1!==n){var r=a[h].substring(0,n),n=a[h].substring(n+1),n=n.replace(/\+/g," ");try{f[r]=g(n)}catch(u){}}}c&&(_.rb=f);return f};_.P.$();
(0,_.N)("gadgets.util.getUrlParameters",_.P.$);
}catch(e){_._DumpException(e)}
try{
_.Mb=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
_.Mb.ba=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};

}catch(e){_._DumpException(e)}
try{
if(window.gapi&&window.gapi.rpc){_.Ob=window.gapi.rpc;_.Ob.call=_.Ob.call;_.Ob.L=_.Ob.register;_.Ob.ab=_.Ob.unregister;_.Ob.jc=_.Ob.setup;_.Ob.Pp=_.Ob.sw;_.Nb=_.Ob}else{_.Qb=function(a){if(a.f in{})return _.v;var c=a.t,f=_.Pb[a.r],a=a.origin;return f&&(f.Pd===c||!f.Pd&&!c)&&(a===f.origin||"*"===f.origin)};_.Ub=function(a,c,f){a=(0,_.Rb)(a);_.Sb[a.name]={Tm:c,we:a.we,Xp:f||_.Qb};(0,_.Tb)()};_.Xb=function(a){var c=a.c;if(!c)return(0,_.x)();var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,
0);_.Vb?a.unshift(f,g+"__cb",_.t,c):a.unshift(f,g+"__cb"+c,_.t);_.Wb.apply(_.t,a)}};_.dc=function(a,c,f,g){var h=_.Yb,l=_.Zb,n=_.Pb[c],r=h,u=(0,_.$b)(c);if(n&&".."!==c){if(u.bh){if(!(l=_.Pb[c].np)){l=_.t;l=_.ac?_.ac.substring(1).split("/"):[_.Yb];r=l.length-1;for(c=window.parent;c!==window.top;){var w=c.parent;if(!r--){for(var y=_.t,C=w.frames.length,G=0;G<C;++G)w.frames[G]==c&&(y=G);l.unshift("{"+y+"}")}c=w}l="/"+l.join("/")}r=l}else r=h="..";l=n.Pd}n=r;if(g&&u){r=_.Qb;if(u.bh)var r=u.id.split("/"),
K=r[r.length-1],L=u.origin,r=function(a){var c=a.origin;return a.f==K&&(L==c||"*"==L)};_.Vb?_.bc["_"+ ++_.cc]=[g,r]:(0,_.Ub)("__cb"+(0,window.String)(++_.cc),g,r);g=_.cc}else g=_.t;f={s:a,f:h,r:n,t:l,c:g,a:f};a=(0,_.Rb)(a);f.s=a.name;f.g=a.we;return f};_.gc=function(a){var c=_.Pb[a];if(c&&c.Hb){var f=c.Eh;c.Eh=[];if(_.ec)f.length&&(f=(0,_.dc)("_processBatch",a,[f]),_.fc.send(a,_.O.stringify(f),c.origin));else for(;f.length;)_.fc.send(a,_.O.stringify(f.shift()),c.origin)}};_.Rb=function(a){return 0===
a.indexOf("legacy__")?{name:a.substring(8),we:_.s}:{name:a,we:_.v}};_.Tb=function(){for(var a=0,c;c=_.jc[a];++a){var f=c.Md,g=f.s,h=_.Sb[g]||_.Sb["*"];if(h&&(_.jc.splice(a,1),--a,f.origin=c.origin,c=(0,_.Xb)(f),f.callback=c,h.Xp(f))){if("__cb"!==g&&!!h.we!=!!f.g)break;f=h.Tm.apply(f,f.a);f!==_.q&&c(f)}}};_.$b=function(a){var c=_.v,a=a.split("|"),f=a[0];0<=f.indexOf("/")&&(c=_.s);return{id:f,origin:a[1]||"*",bh:c}};_.mc=function(a,c){var f=(0,_.$b)(a),a=f.id;if(!_.Pb.hasOwnProperty(a)){var g=_.Zb,
h=_.t;f.bh?(g=_.t,h=f.origin):".."!==a?(g=window.document.getElementById(a).src,h=_.Mb.ba(g),g=(0,_.kc)(g).rpctoken):h=_.Mb.ba(_.lc);f.origin&&(h=f.origin);_.Pb[a]={Pd:g,Eh:[],origin:h,np:c,hk:function(){var c=a;_.Pb[c].Hb=1;(0,_.gc)(c)}};_.fc.jc(a,_.Pb[a].hk)}return _.Pb[a].hk};_.nc=function(){return"function"===typeof window.postMessage||"object"===typeof window.postMessage};_.Wb=function(a,c,f,g){a=a||"..";(0,_.mc)(a);var a=a.split("|",1)[0],h=[].slice.call(arguments,3),h=(0,_.dc)(c,a,h,f);_.Pb[a].Eh.push(h);
var l=a;_.oc[l]||(_.oc[l]=window.setTimeout(function(){_.oc[l]=_.v;(0,_.gc)(l)},0))};_.pc={call:_.Wb,L:_.Ub,ab:function(a){a=(0,_.Rb)(a);delete _.Sb[a.name]},jc:_.mc,Pp:_.nc};if((0,_.nc)()){_.ec=_.v;_.cc=0;_.jc=[];_.Pb={};_.Sb={};_.kc=_.P.$;_.qc=(0,_.kc)();_.Zb=_.qc.rpctoken;_.lc=_.qc.parent||window.document.referrer;_.Yb=window!==window.top&&window.name||"..";_.ac=_.t;_.oc={};_.rc={Nm:function(a,c){var f=_.O.parse(a);_.jc.push({Md:f,origin:c});(0,_.Tb)()},Gn:function(a){var c=window;"/"==a.charAt(0)&&
(a=a.substring(1),c=window.top);for(a=a.split("/");a.length;){var f;f=a.shift();"{"==f.charAt(0)&&"}"==f.charAt(f.length-1)&&(f=f.substring(1,f.length-1));if(".."===f)c=c.parent;else if(".."!==f&&c.frames[f])c=c.frames[f],"postMessage"in c||(0,_.m)("Not a window");else return _.t}return c},b:_.Yb,Ni:function(a){return(a=_.Pb[a])&&a.Pd},d:function(a){_.ac=a}};_.sc=function(a){a=_.O.parse(a);return a!=_.t&&"object"===typeof a&&!!a.g};_.uc=function(a){var c=(0,window.String)(a.data),f=0!==c.indexOf("!_");
f||(c=c.substring(2));var g=(0,_.sc)(c);if(f==g){if(!g&&(f=c,g=_.t,0==f.indexOf("{h:'")&&f.indexOf("'}")==f.length-2&&(g=(0,window.unescape)(f.substring(4,f.length-2))),f=g)){if(_.tc[f])_.tc[f]();return}var h=a.origin;window.setTimeout(function(){_.rc.Nm(c,h)},0)}};_.tc={};_.vc=_.t;(_.vc=window.addEventListener)?(0,_.vc)("message",_.uc,_.v):(_.vc=window.attachEvent)&&(0,_.vc)("onmessage",_.uc);window.___jsl=window.___jsl||{};_.wc=window.___jsl;_.wc.RPMQ=_.wc.RPMQ||[];_.wc.RPMQ.push(_.uc);if(window!==
window.parent){_.xc=window.parent;_.yc="{h:'"+(0,window.escape)(window.name)+"'}";_.zc=(0,_.sc)(_.yc)?"":"!_";_.xc.postMessage(_.zc+_.yc,"*")}_.fc={jc:function(a,c){".."==a?c():_.tc[a]=c},send:function(a,c,f){var a=_.rc.Gn(a),g=(0,_.sc)(c)?"":"!_";a.postMessage(g+c,f)}};_.bc={};_.Vb=_.s;(0,_.Ub)("__cb",function(a,c){var f=_.bc["_"+a];f&&f[1](this)&&f[0].call(this,c)},(0,_.ca)(_.s));(0,_.Ub)("_processBatch",function(a){for(;a.length;){var c=a.shift();_.jc.push({Md:c,origin:this.origin})}(0,_.Tb)()}, (0,_.ca)(_.s));(0,_.mc)("..")}_.Nb=_.pc}_.Ac=_.Nb;

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Dc=function(a){if("complete"===_.Za.readyState)a();else{var c=_.v,f=function(){if(!c)return c=_.s,a.apply(this,arguments)};_.Ya.addEventListener?(_.Ya.addEventListener("load",f,_.v),_.Ya.addEventListener("DOMContentLoaded",f,_.v)):_.Ya.attachEvent&&(_.Ya.attachEvent("onreadystatechange",function(){"complete"===_.Za.readyState&&f.apply(this,arguments)}),_.Ya.attachEvent("onload",f))}};_.Ec=_.Ec||{};_.Ec.tk=_.t;_.Ec.Mj=_.t;_.Ec.hf=_.t;_.Ec.frameElement=_.t;
_.Ec=_.Ec||{};
if(!_.Ec.Vh){_.Hc=function(a){var c=_.O.parse(a.data);if(c&&c.f){var f=_.Q.Xb(c.f);(!_.Fc||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.Gc)(c,a.origin)}};_.Fc=_.s;_.Ec.Vh={Ji:(0,_.ca)("wpm"),b:(0,_.ca)(_.s),aa:function(a,c){_.Jb.L("rpc",_.t,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.Fc=_.v});_.Gc=a;_.Ic=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.Hc,_.v):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.Hc);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.Hc);(0,_.Ic)("..",_.s);return _.s},jc:function(a){(0,_.Ic)(a,_.s);return _.s},call:function(a,c,f){var g=_.Q.Xb(a),h=_.Q.ii(a);g?window.setTimeout(function(){h.postMessage(_.O.stringify(f),g)},0):".."!=a&&(0,_.fb)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.s}}};
_.Ec=_.Ec||{};
if(!_.Ec.Te){_.Jc=_.Ec;_.Mc=function(a,c){function f(){a.apply({},arguments)}_.Kc[c]=_.Kc[c]||f;return _.Lc+"."+c};_.Tc=function(){if(_.Nc===_.t&&window.document.body&&_.Oc){var a=_.Oc+"?cb="+window.Math.random()+"&origin="+_.Pc+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.Qc+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.Nc=c.firstChild}++_.Rc;_.Sc!==_.t&&(_.Nc!==_.t||50<=_.Rc)?window.clearTimeout(_.Sc):_.Sc=window.setTimeout(_.Tc,100)};_.Zc=function(){_.Vc[".."]||((0,_.Wc)(".."),_.Xc++,50<=_.Xc&&_.Yc!==_.t?(window.clearTimeout(_.Yc),_.Yc=_.t):_.Yc=window.setTimeout(_.Zc,100))};_.ad=function(){if(_.Nc!==_.t&&_.Nc.setup)for(;0<_.$c.length;){var a=_.$c.shift(),c=a.Rp;_.Nc.setup(a.Pd,".."===c?_.Q.Qf:c,".."===c?"INNER":"OUTER")}_.Sc!==
_.t&&window.clearTimeout(_.Sc);_.Sc=_.t};_.bd=function(){!_.Vc[".."]&&_.Yc===_.t&&(_.Yc=window.setTimeout(_.Zc,100))};_.cd=function(a,c,f){var c=_.Q.Xb(a),g=_.Q.Ub(a);_.Nc["sendMessage_"+(".."===a?_.Q.Qf:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.Nc,_.O.stringify(f),c);return _.s};_.fd=function(a,c){var f=_.O.parse(a),g=f._scr;g?((0,_.dd)(g,_.s),_.Vc[g]=_.s,".."!==g&&(0,_.Wc)(g,_.s)):window.setTimeout(function(){(0,_.ed)(f,c)},0)};_.Wc=function(a,c){var f=_.Q.Qf,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.cd)(a,f,g)};_.Qc="___xpcswf";_.Oc=_.t;_.gd=_.v;_.ed=_.t;_.dd=_.t;_.Nc=_.t;_.$c=[];_.Sc=_.t;_.Rc=0;_.Xc=0;_.Yc=_.t;_.Vc={};_.Pc=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.hd=window.___jsl._fm={};_.Lc="___jsl._fm";_.Kc=_.hd;_.Jb.L("rpc",_.t,function(a){_.gd&&(_.Oc=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.Mc)(_.ad,"ready");(0,_.Mc)(_.bd,"setupDone");(0,_.Mc)(_.fd,"receiveMessage");_.Jc.Te={Ji:(0,_.ca)("flash"),b:(0,_.ca)(_.s), aa:function(a,c){_.ed=a;_.dd=c;return _.gd=_.s},jc:function(a,c){_.$c.push({Pd:c,Rp:a});_.Nc===_.t&&_.Sc===_.t&&(_.Sc=window.setTimeout(_.Tc,100));return _.s},call:_.cd,nm:_.fd,d:_.ad,i:_.bd}};
if(!window.gadgets||!window.gadgets.rpc){_.nd=function(a,c){if(!_.id[a]){var f=_.jd;c||(f=_.kd);_.id[a]=f;for(var g=_.ld[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=_.md[a];f.call(a,l.f,l)}_.ld[a]=[]}};_.sd=function(a,c,f,g,h){function l(){_.od=_.s}if(!_.md[c]||_.md[c]!==f)(0,_.fb)("Invalid auth token. "+_.md[c]+" vs "+f),(0,_.pd)(c,2);h.onunload=function(){_.qd[c]&&!_.od&&((0,_.pd)(c,1),_.Q.Id(c))};_.rd||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",l,_.v):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",l),_.rd=_.s);g=_.O.parse((0,window.decodeURIComponent)(g))};_.vd=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.md[a.f]&&_.md[a.f]!==a.t&&((0,_.fb)("Invalid auth token. "+_.md[a.f]+" vs "+a.t),(0,_.pd)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.nd)(a.f,_.s)},0);else{a.c&&(a.callback=function(c){_.Q.call(a.f,(a.g?"legacy__":"")+"__cb",_.t,a.c,c)});if(c){var f=(0,_.td)(c);a.origin=
c;var g=a.r;if(!g||(0,_.td)(g)!=f)g=c;a.referer=g}f=(_.ud[a.s]||_.ud[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.Q.call(a.f,"__cb",_.t,a.c,f)}};_.td=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+
1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.wd=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.t}}return _.t};_.xd=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.wd)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.t};
_.yd=function(a,c){if(_.qd[a]!==_.s){"undefined"===typeof _.qd[a]&&(_.qd[a]=0);var f=(0,_.xd)(a);(".."===a||f!=_.t)&&_.jd.jc(a,c)===_.s?_.qd[a]=_.s:_.qd[a]!==_.s&&10>_.qd[a]++?window.setTimeout(function(){(0,_.yd)(a,c)},500):(_.id[a]=_.kd,_.qd[a]=_.s)}};_.Ad=function(a){(a=_.zd[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.Cd=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.zd[a]=c;"undefined"!==typeof f&&(_.Bd[a]=!!f)};_.Dd=function(a,c){c=c||"";_.md[a]=(0,window.String)(c);(0,_.yd)(a,c)};_.Gd=function(a){a=(a.passReferrer||"").split(":",2);_.Ed=a[0]||"none";_.Fd=a[1]||"origin"};_.Hd=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.jd=_.Ec.hf||_.kd,_.jd.aa(_.vd,_.nd))};_.Jd=
function(a,c,f){if(".."===a){var g=f||_.Id.rpctoken||_.Id.ifpctok||"",a=function(a){a=a&&a.rpc||{};(0,_.Gd)(a);var f=a.parentRelayUrl||"",f=(0,_.td)(_.Id.parent||c)+f;(0,_.Cd)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.Hd)(a);(0,_.Dd)("..",g)};!_.Id.parent&&c?a({}):_.Jb.L("rpc",_.t,a)}else a:{var h=_.t;if("/"!=a.charAt(0)){if(!_.P)break a;(h=window.document.getElementById(a))||(0,_.m)((0,window.Error)("g`"+a))}var h=h&&h.src,l=c||_.Q.ba(h);(0,_.Cd)(a,l);h=_.P.$(h);(0,_.Dd)(a,f||
h.rpctoken)}};_.ud={};_.zd={};_.Bd={};_.md={};_.Kd=0;_.Ld={};_.qd={};_.Id={};_.id={};_.ld={};_.Ed=_.t;_.Fd=_.t;_.Md=window.top!==window.self;_.Nd=window.name;_.pd=(0,_.x)();_.Od=window.console;_.Pd=_.Od&&_.Od.log&&function(a){_.Od.log(a)}||(0,_.x)();_.Qd=function(a){return function(){(0,_.Pd)(a+": call ignored")}};_.kd={getCode:(0,_.ca)("noop"),isParentVerifiable:(0,_.ca)(_.s),init:(0,_.Qd)("init"),setup:(0,_.Qd)("setup"),call:(0,_.Qd)("call")};_.P&&(_.Id=_.P.$());_.od=_.v;_.rd=_.v;_.jd=function(){if("flash"==
_.Id.rpctx)return _.Ec.Te;if("rmr"==_.Id.rpctx)return _.Ec.tk;var a="function"===typeof window.postMessage?_.Ec.Vh:"object"===typeof window.postMessage?_.Ec.Vh:window.ActiveXObject?_.Ec.Te?_.Ec.Te:_.Ec.Mj?_.Ec.Mj:_.Ec.hf:0<window.navigator.userAgent.indexOf("WebKit")?_.Ec.tk:"Gecko"===window.navigator.product?_.Ec.frameElement:_.Ec.hf;a||(a=_.kd);return a}();_.ud[""]=function(){(0,_.Pd)("Unknown RPC service: "+this.s)};_.ud.__cb=function(a,c){var f=_.Ld[a];f&&(delete _.Ld[a],f.call(this,c))};_.Q=
{ja:function(a){"function"===typeof a.rp&&(_.pd=a.rp)},L:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("h"));""===a&&(0,_.m)((0,window.Error)("i"));_.ud[a]=c},ab:function(a){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("j"));""===a&&(0,_.m)((0,window.Error)("k"));delete _.ud[a]},Ce:function(a){_.ud[""]=a},Ie:function(){delete _.ud[""]},ce:(0,_.x)(),call:function(a,c,f,g){var a=a||"..",h="..";".."===a?h=_.Nd:"/"==a.charAt(0)&&(h=_.Q.ba(window.location.href),h="/"+_.Nd+(h?
"|"+h:""));++_.Kd;f&&(_.Ld[_.Kd]=f);var l={s:c,f:h,c:f?_.Kd:0,a:window.Array.prototype.slice.call(arguments,3),t:_.md[a],l:!!_.Bd[a]},n;a:if("bidir"===_.Ed||"c2p"===_.Ed&&".."===a||"p2c"===_.Ed&&".."!==a){n=window.location.href;var r="?";if("query"===_.Fd)r="#";else if("hash"===_.Fd)break a;r=n.lastIndexOf(r);r=-1===r?n.length:r;n=n.substring(0,r)}else n=_.t;n&&(l.r=n);".."!==a&&(0,_.wd)(a)==_.t&&!window.document.getElementById(a)||(n=_.id[a],!n&&(0,_.wd)(a)!==_.t&&(n=_.jd),0===c.indexOf("legacy__")&&
(n=_.jd,l.s=c.substring(8),l.c=l.c?l.c:_.Kd),l.g=_.s,l.r=h,n?(_.Bd[a]&&(n=_.Ec.hf),n.call(a,h,l)===_.v&&(_.id[a]=_.kd,_.jd.call(a,h,l))):_.ld[a]?_.ld[a].push(l):_.ld[a]=[l])},ie:_.Ad,gd:_.Cd,fd:_.Dd,Dc:_.Jd,Ub:function(a){return _.md[a]},Id:function(a){delete _.zd[a];delete _.Bd[a];delete _.md[a];delete _.qd[a];delete _.id[a]},he:function(){return _.jd.Ji()},Ae:function(a,c){4<a.length?_.jd.nm(a,_.vd):_.sd.apply(_.t,a.concat(c))},Be:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.vd)(a)},
0)},ba:_.td,Xb:function(a){var c=_.t,c=(0,_.Ad)(a);c||(c=(c=(0,_.wd)(a))?c.origin:".."==a?_.Id.parent:window.document.getElementById(a).src);return(0,_.td)(c)},aa:function(){_.jd.aa(_.vd,_.nd)===_.v&&(_.jd=_.kd);_.Md?(0,_.Jd)(".."):_.Jb.L("rpc",_.t,function(a){a=a.rpc||{};(0,_.Gd)(a);(0,_.Hd)(a)})},ii:_.xd,mm:_.wd,b:"__ack",Qf:_.Nd||"..",j:0,i:1,d:2};_.Q.aa()}else if("undefined"==typeof _.Q||!_.Q)_.Q=window.gadgets.rpc,_.Q.ja=_.Q.config,_.Q.L=_.Q.register,_.Q.ab=_.Q.unregister,_.Q.Ce=_.Q.registerDefault,
_.Q.Ie=_.Q.unregisterDefault,_.Q.ce=_.Q.forceParentVerifiable,_.Q.call=_.Q.call,_.Q.ie=_.Q.getRelayUrl,_.Q.gd=_.Q.setRelayUrl,_.Q.fd=_.Q.setAuthToken,_.Q.Dc=_.Q.setupReceiver,_.Q.Ub=_.Q.getAuthToken,_.Q.Id=_.Q.removeReceiver,_.Q.he=_.Q.getRelayChannel,_.Q.Ae=_.Q.receive,_.Q.Be=_.Q.receiveSameDomain,_.Q.ba=_.Q.getOrigin,_.Q.Xb=_.Q.getTargetOrigin,_.Q.ii=_.Q._getTargetWin,_.Q.mm=_.Q._parseSiblingId;
(0,_.N)("gadgets.rpc.config",_.Q.ja);(0,_.N)("gadgets.rpc.register",_.Q.L);(0,_.N)("gadgets.rpc.unregister",_.Q.ab);(0,_.N)("gadgets.rpc.registerDefault",_.Q.Ce);(0,_.N)("gadgets.rpc.unregisterDefault",_.Q.Ie);(0,_.N)("gadgets.rpc.forceParentVerifiable",_.Q.ce);(0,_.N)("gadgets.rpc.call",_.Q.call);(0,_.N)("gadgets.rpc.getRelayUrl",_.Q.ie);(0,_.N)("gadgets.rpc.setRelayUrl",_.Q.gd);(0,_.N)("gadgets.rpc.setAuthToken",_.Q.fd);(0,_.N)("gadgets.rpc.setupReceiver",_.Q.Dc);
(0,_.N)("gadgets.rpc.getAuthToken",_.Q.Ub);(0,_.N)("gadgets.rpc.removeReceiver",_.Q.Id);(0,_.N)("gadgets.rpc.getRelayChannel",_.Q.he);(0,_.N)("gadgets.rpc.receive",_.Q.Ae);(0,_.N)("gadgets.rpc.receiveSameDomain",_.Q.Be);(0,_.N)("gadgets.rpc.getOrigin",_.Q.ba);(0,_.N)("gadgets.rpc.getTargetOrigin",_.Q.Xb);

}catch(e){_._DumpException(e)}
try{
_.Rd=_.Mb=_.Mb||{};_.Sd={Xh:"bsh",$h:"h"};window.___jsl=window.___jsl||{};_.Rd.Yd={Ym:function(){return window.___jsl[_.Sd.Xh]},Fg:function(){return window.___jsl[_.Sd.$h]},Df:function(a){window.___jsl[_.Sd.Xh]=a},Cp:function(a){window.___jsl[_.Sd.$h]=a}};

}catch(e){_._DumpException(e)}
try{
_.Td=window.iframer=window.iframer||{};_.R=window.iframes=window.iframes||{};
}catch(e){_._DumpException(e)}
try{
_.Ud=function(a){var c=(0,_.J)("googleapis.config/sessionIndex");c==_.t&&(c=window.__X_GOOG_AUTHUSER);if(c==_.t){var f=window.google;f&&(c=f.authuser)}c==_.t&&(a==_.t&&(a=window.location.href),c=a?(0,_.Da)(a,"authuser")||_.t:_.t);return c==_.t?_.t:(0,window.String)(c)};
_.Vd=function(a,c,f){a=(0,window.String)(a);if(((0,_.Da)(a,"authuser")||_.t)!=_.t||((0,_.Da)(a,"hd")||_.t)!=_.t)return a;c=(0,_.Ud)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],n=h[4],r=h[5];h[3]=="/"+f&&(g=(l||"")+(n||"/")+(r||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],r=h[6],c!=_.t&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(r||"")),g}f=c==_.t?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.Wd=_.Vd;
}catch(e){_._DumpException(e)}
try{
_.Xd=function(a){var c=(0,_.Da)(a.location.href,"urlindex");if(c=(0,_.qa)(_.Ma,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};_.R.F=_.R.F||{};_.R.F.Yh="friendlyIframe";_.R.F.Am=function(a){try{return!!a.document}catch(c){}return _.v};_.R.F.uc=function(a){var c=a.parent;return a!=c&&_.R.F.Am(c)?_.R.F.uc(c):a};_.R.F.yj=function(a){try{return _.R.F.uc(a)!=a&&!!a.frameElement&&a.frameElement.name==_.R.F.Yh}catch(c){return _.v}};_.R.F.jo=function(a){var c=a.userAgent||"",a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Zd=window.ToolbarApi,_.Zd.ka=window.ToolbarApi.getInstance,_.Zd.prototype=window.ToolbarApi.prototype,_.A=_.Zd.prototype,_.A.Zj=_.Zd.prototype.openWindow,_.A.yi=_.Zd.prototype.closeWindow,_.A.Dk=_.Zd.prototype.setOnCloseHandler,_.A.wi=_.Zd.prototype.canClosePopup,_.A.nk=_.Zd.prototype.resizeWindow;else{_.$d=_.t;_.Zd=(0,_.x)();_.Zd.ka=function(){!_.$d&&(window.external&&window.external.GTB_IsToolbar)&&(_.$d=new _.Zd);return _.$d};_.A=_.Zd.prototype;_.A.Zj=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.A.yi=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.A.Dk=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.A.wi=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.A.nk=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Zd;window.ToolbarApi.getInstance=_.Zd.ka};
if(!window.iframes||!window.iframes.open){_.be=/^[-_.0-9A-Za-z]+$/;_.ce={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.de={onBeforeParentOpen:"beforeparentopen"};_.ee={longdesc:_.s,name:_.s,src:_.s,frameborder:_.s,marginwidth:_.s,marginheight:_.s,scrolling:_.s,align:_.s,height:_.s,width:_.s,id:_.s,"class":_.s,style:_.s,title:_.s,tabindex:_.s,hspace:_.s,vspace:_.s,allowtransparency:_.s};_.fe=
{onOpen:function(a){var c=a.ga();a.Na(c.container||c.element);return a},onClose:function(a){a.remove()}};_.ge=window.encodeURIComponent||window.escape;_.he=function(a){(0,_.fb)(a.join(""))};_.ie=function(){_.R.vj++;return["I",_.R.vj,"_",(new window.Date).getTime()].join("")};_.je=function(a){var c={allowtransparency:"true",frameborder:0,hspace:0,marginheight:0,marginwidth:0,scrolling:"no",style:"",tabindex:"0",vspace:0,width:"100%"},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);return c};_.le=function(a,
c,f){f=f||{};f.id||(f.id=a);f.name||(f.name=a);f.src||(f.src=c);a=(0,_.je)(f);c=[];c.push("<iframe ");for(var g in a)a.hasOwnProperty(g)&&(_.ee[g.toLowerCase()]?(f=(0,window.String)(a[g]),c.push(g),c.push('="'),c.push(_.P.be("style"==g.toLowerCase()?(0,_.ke)(f):f)),c.push('" ')):(0,_.he)(['Iframe attribute "',g,'" not allowed.']));c.push("></iframe>");return c.join("")};_.ke=function(a){if(!a)return"";for(var c=[],a=a.split(";"),f=0,g=a.length;f<g;++f){var h=a[f];0==h.length&&f+1==g||(h=h.split(":"),
2==h.length&&h[0].match(/^[ a-zA-Z_-]+$/)&&h[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?c.push(h.join(":")):(0,_.he)(['Iframe style "',a[f],'" not allowed.']))}return c.join(";")};_.me=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname,f=c.lastIndexOf("/");
return c.substring(0,f+1)+a};_.ne=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.O.stringify(a):a};_.oe=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.t,g.lc=a):(g.hash=a.substring(h+1),g.lc=a.substring(0,h));a=g.lc.indexOf("?");-1==a?g.$a=_.t:(g.$a=g.lc.substring(a+1),g.lc=g.lc.substring(0,a));var a=f?g.hash?[g.hash]:[]:g.$a?[g.$a]:[],l;for(l in c)c.hasOwnProperty(l)&&(h=(0,_.ne)(c[l]),a.push([(0,_.ge)(l),(0,_.ge)(h)].join("=")));f?g.hash=a.join("&"):
g.$a=a.join("&");return g.lc+(g.$a?"?"+g.$a:"")+(g.hash?"#"+g.hash:"")};_.pe=(0,_.x)();_.qe=function(){var a=(0,_.Ud)(_.q);return a!==_.q&&a!==_.t&&""!==a?"u/"+a+"/":""};_.re=function(a){var c=_.P.$().jsh||_.Mb.Yd.Fg();!a.jsh&&c&&(a.jsh=c);c=_.P.$()._bsh||_.Mb.Yd.Ym();!a._bsh&&c&&(a._bsh=c)};_.se=function(a){a&&a.match(_.be)&&(0,_.Va)("googleapis.config/gcv",a)};_.ue=function(a){_.Mb.Yd.Cp(a)};_.ve=function(a){_.Mb.Yd.Df(a)};_.we=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);
return f};_.xe=function(a){_.R.Bf[a]||(_.R.Bf[a]={},_.Q.L(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,l=_.R.Bf[a][g],n;l&&window.Object.hasOwnProperty.call(l,c)?n=l[c]:window.Object.hasOwnProperty.call(_.R.zd,a)&&(n=_.R.zd[a]);if(n)return g=window.Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}(0,_.he)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,
'".']);return _.t}));return _.R.Bf[a]};_.ye=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var r=c,u=f,w=a[n],y=g,C=(0,_.xe)(n);C[r]=C[r]||{};y=_.P.Cd(y,w);w._iframe_wrapped_rpc_&&(y._iframe_wrapped_rpc_=_.s);C[r][u]=y;l.push(n)}if(h)for(n in _.R.zd)_.R.zd.hasOwnProperty(n)&&l.push(n);return l.join(",")};_.ze=function(a,c,f){function g(g){var l=window.Array.prototype.slice.call(arguments,0),n=l[l.length-1];if("function"===typeof n){var r=n;l.pop()}l.unshift(c,a,r,f);var u;a:if(".."==
c||window.document.getElementById(c))u=window;else{for(n=0;n<_.R.zg.length;n++)try{var w=_.R.zg[n];if(w&&w.document&&(w.document||window.document).getElementById(c)){u=w;break a}}catch(y){}u=_.t}u?u==window?_.Q.call.apply(_.Q,l):(u=u.gadgets.rpc,u.call.apply(u,l)):(0,_.he)(["RPC ",a,' not sent: target iframe "',c,'" not found.'])}g._iframe_wrapped_rpc_=_.s;return g};_.Ae=function(a,c,f){var g={};if(a&&a._methods)for(var a=a._methods.split(","),h=0;h<a.length;h++){var l=a[h];g[l]=(0,_.ze)(l,c,f)}return g};
_.Be=function(a){return a&&a.disableMultiLevelParentRelay?_.v:_.Td&&_.Td._open&&"inline"!=a.style&&a.inline!==_.s&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.Ce=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};_.De=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};_.Ee=function(a,c,f,g,h,l,n,r){if(":"==a.charAt(0)){var a="iframes/"+a.substring(1),u=
a+"/params",w={},y=(0,_.J)(u);(0,_.Va)(u,y||w);(w=(0,_.J)(a+"/url"))?(u=a+"/url",w=w||"",w=w.replace(/:session_prefix:/g,(0,_.qe)()),w=w.replace(/:session_index:/g,(0,_.Ud)(_.q)||"0"),w=w.replace(/:socialhost:/g,(0,_.J)("iframes/:socialhost:")),(0,_.Va)(u,(0,_.me)(w)),a=(0,_.J)(a)):((0,_.he)(["URL not present in iframe configuration."]),a={})}else a={url:(0,_.me)(a)};this.ja=a;this.openParams=this.k=c;this.Sa=f||{};this.b=g;this.p=_.v;this.Co(c.style);this.i={};this.dd(function(){this.om(h);l&&this.Yf("close",
l)});this.bc=this.ac=n;this.yh=(r||[]).slice();n&&this.yh.unshift(n.R())};_.A=_.Ee.prototype;_.A.ga=(0,_.z)("k");_.A.Pa=(0,_.z)("Sa");_.A.Vb=(0,_.z)("b");_.A.Aa=(0,_.z)("bc");_.A.Co=function(a){if(!this.p)if(a=a&&!_.R.Ge[a]&&_.R.lg[a]){this.B=[];var c=this;a(function(){c.p=_.s;for(var a=0,g=c.B.length;a<g;++a)c.B[a].call(c)})}else this.p=_.s};_.A.dd=function(a){this.p?a.call(this):this.B.push(a)};_.A.om=function(a){var c=this.hn();if(c){if("function"===typeof c)c=c(this);else{var f={},g;for(g in c){var h=
c[g];f[g]="function"===typeof h?_.P.Cd(c,h,this):h}c=f}for(var l in a)f=c[l],"function"===typeof f&&this.Yf(a[l],_.P.Cd(c,f))}};_.A.ea=function(a,c){this.dd(function(){this.Yf(a,c)})};_.A.Yf=function(a,c){this.i[a]=this.i[a]||[];this.i[a].push(c)};_.A.Ib=function(a,c){this.dd(function(){var f=this.i[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.A.rb=function(a,c){var f,g=this.i[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),l=0,n=g.length;l<n;++l)try{f=
g[l].apply({},h)}catch(r){(0,_.he)(['Exception when calling callback "',a,'" with exception "',r.name,": ",r.message,'".'])}return f};_.A.hn=function(){var a=this.k.style;return a&&_.R.Ge[a]?_.R.Ge[a]:a?((0,_.ob)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),_.t):_.fe};_.A.Ye=function(a){return"number"==typeof a?{value:a,Mc:a+"px"}:"100%"==a?{value:100,Mc:"100%",Ej:_.s}:_.t};_.A.Wk=function(){return(0,_.oe)(this.ja.url,this.Sa,_.v)};_.S=function(a,c,f,g,h,l,n){_.Ee.call(this,
a,c,f,g,_.ce,h,l,n);this.id=c.id||(0,_.ie)();this.La=!!c.rpcToken;this.W=c.rpcToken||window.Math.round(1E9*(0,_.yb)());var a=this.Sa,c={},f=this.ja.params||{},r;for(r in a)"#"==r.charAt(0)&&(c[r.substring(1)]=a[r]),0==r.indexOf("fr-")&&(c[r.substring(3)]=a[r]),"#"==f[r]&&(c[r]=a[r]);for(var u in c)delete a["fr-"+u],delete a["#"+u],delete a[u];this.da=c;this.D={};this.dd(function(){this.rb("open");(0,_.we)(this.D,this)})};(0,_.De)(_.S,_.Ee);_.A=_.S.prototype;_.A.Na=function(a,c){if(!this.ja.url)return(0,_.he)(["Cannot open iframe, empty URL."]),
this;var f=window.location.protocol+"//"+window.location.host,g=this.id;(0,_.re)(this.Sa);var h=(0,_.we)(this.b);h._ready=this.tf;h._close=this.close;h._open=this.$j;h._resizeMe=this.ok;h._renderstart=this.Vj;var l=this.da;l.id=g;l.parent=f;l.rpctoken=this.W;l._methods=(0,_.ye)(h,g,"",this,_.s);f=this.Wk();f=(0,_.oe)(f,l,_.s);a="string"===typeof a?window.document.getElementById(a):a;if(this.ga().allowPost&&2E3<f.length)this.Xo(a,g,l,c);else if(this.La)a.innerHTML=(0,_.le)(g,f,c);else if(_.R.F.jo(window.navigator||
{})){a.innerHTML=(0,_.le)(g,"about:blank",c);a.firstChild.src=f;try{a.firstChild.contentDocument.location.href=f}catch(n){}}else{l=(0,_.le)(g,f,c);try{a.innerHTML=l}catch(r){h=window.document.createElement("div");for(h.innerHTML=l;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(h.firstChild)}}this.j=a;this.d=a.firstChild;_.R.Vc[g]=this;_.Q.fd(g,this.W);_.Q.gd(g,f);return this};_.A.wm=function(a){var c=a.id,f=a.src,g=/#(?:.*&)?rpctoken=(\d+)/.exec(f),g=g&&g[1];this.id=c;this.W=g;this.j=a.parentNode;
this.d=a;_.R.Vc[c]=this;a=(0,_.we)(this.b);a._ready=this.tf;a._close=this.close;a._open=this.$j;a._resizeMe=this.ok;a._renderstart=this.Vj;(0,_.ye)(a,c,"",this,_.s);_.Q.fd(c,g);_.Q.gd(c,f);return this};_.A.vm=function(a){var a=(0,_.je)(a||{}),c;for(c in a)window.Object.prototype.hasOwnProperty.call(a,c)&&("style"==c?this.d.style.cssText=a[c]:this.d.setAttribute(c,a[c]))};_.A.Xo=function(a,c,f,g){a.innerHTML=(0,_.le)(c,"",g);var h;-1!=window.navigator.userAgent.indexOf("WebKit")&&(h=a.firstChild,g=
(0,_.le)(c+"_inner","",{style:"display:none"}),h=h.contentWindow.document,h.open(),h.write(g));g=(0,_.oe)(this.ja.url,f,_.s);f=this.Sa||{};g={action:g,method:"POST",target:c};c=window.document.createElement("form");c.style.display="none";for(var l in g)g.hasOwnProperty(l)&&(c[l]=g[l]);for(var n in f)f.hasOwnProperty(n)&&(l=window.document.createElement("input"),l.type="hidden",l.name=n,l.value=f[n],c.appendChild(l));a.appendChild(c);c.submit();c.parentNode.removeChild(c);h&&h.close()};_.A.Ua=function(a,
c){this.D[a]=c};_.A.R=(0,_.z)("id");_.A.X=(0,_.z)("d");_.A.S=(0,_.z)("j");_.A.Lb=(0,_.ba)("j");_.A.tf=function(a){var c=(0,_.Ae)(a,this.id,"");this.bc&&"function"==typeof this.b._ready&&(a._methods=(0,_.ye)(c,this.bc.R(),this.id,this,_.v),this.b._ready(a));(0,_.we)(a,this);(0,_.we)(c,this);this.rb("ready",a)};_.A.Vj=function(a){this.rb("renderstart",a)};_.A.dp=function(a,c,f){f._methods=(0,_.ye)((0,_.Ae)(f,a,""),this.id,a,this,_.v);c(f)};_.A.close=function(a){a=this.rb("close",a);if(_.R.F.yj(window)){var c=
window.frameElement,f=c.parentNode;"friendlyIframeContainer"==f.className?(0,_.Ce)(f):(0,_.Ce)(c)}delete _.R.Vc[this.id];return a};_.A.remove=function(){(0,_.Ce)(window.document.getElementById(this.id))};_.A.$j=function(a){var c=(0,_.Ae)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.j);if((0,_.Be)(a.openParams))new _.Fe(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else if("expandable"===a.openParams.style&&a.openParams.inline!==
_.s&&_.R.F.uc(window)!=window)this.Wo(a,c);else{var f=new _.S(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;f.dd(function(){var a=g.ui(f);c._onopen(a)})}};_.A.Wo=function(a,c){var f=_.R.F.uc(window),g={height:0,name:_.R.F.Yh,style:"left:0;position:absolute;top:0;z-index:-10000",width:0},h=f.document.createElement("ins");h.className="friendlyIframeContainer";h.innerHTML=(0,_.le)("","about:blank",g);f.document.body.appendChild(h);f=h.firstChild.contentWindow;_.R.zg.push(f);
g=f.document;h=['<html><body><script src="',_.R.Dg(),'"><\/script></body></html>'].join("");g.open();g.write(h);g.close();g=a.openParams.id||(0,_.ie)();a.openParams.id=g;g=_.P.Cd(this,this.dp,g,c._ready);c._ready=g;var l=_.P.Cd(f,function(f,g){if(!f.te||"function"!=typeof f.te.open)return _.v;var h=f.te.open(a.url,a.openParams,a.params,c,c._onclose,g),h=g.ui(h);c._onopen(h);return _.s},f,this),n=window.setInterval(function(){l()&&window.clearInterval(n)},10)};_.A.ui=function(a){var c={childId:a.R()},
f=a.D;f._toclose=a.close;c._methods=(0,_.ye)(f,this.id,a.id,a,_.v);return c};_.A.ok=function(a){if(this.rb("resize",a)===_.q&&this.d){var c=this.Ye(a.width);c!=_.t&&(this.d.style.width=c.Mc);a=this.Ye(a.height);a!=_.t&&(this.d.style.height=a.Mc);if(this.d.parentElement&&(c!=_.t&&c.Ej||a!=_.t&&a.Ej))this.d.parentElement.style.display="block"}};_.Fe=function(a,c,f,g,h,l,n){_.Ee.call(this,a,c,f,g,_.de,h,l,n);this.url=a;this.d=_.t;this.I=(0,_.ie)();this.dd(function(){this.rb("beforeparentopen");var a=
(0,_.we)(this.b);a._onopen=this.Ba;a._ready=this.tf;a._onclose=this.na;this.Sa._methods=(0,_.ye)(a,"..",this.I,this,_.s);var a={},c;for(c in this.Sa)a[c]=(0,_.ne)(this.Sa[c]);var f=this.ja.url;if(this.k.hideUrlFromParent){c=window.name;var g=f,f=this.Wk(),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];a["#opener"]&&h["#urlindex"]!=_.q?(a["#opener"]=c+","+a["#opener"],c={url:g,Sa:a}):(g=(0,_.qa)(_.Ma,"fUrl",[]),h=g.length,g[h]=f,_.Ma.rUrl=_.Xd,a["#opener"]=c,
a["#urlindex"]=h,c=_.Mb.ba(_.Ya.location.href),f=(0,_.J)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Sa:a});f=c.url;a=c.Sa}_.Td._open({url:f,openParams:this.k,params:a,proxyId:this.I,openedByProxyChain:this.yh})})};(0,_.De)(_.Fe,_.Ee);_.Fe.prototype.Mi=(0,_.z)("d");_.Fe.prototype.Ba=function(a){this.d=a.childId;var c=(0,_.Ae)(a,"..",this.d);(0,_.we)(c,this);this.close=c._toclose;_.R.Vc[this.d]=this;this.bc&&this.b._onopen&&(a._methods=(0,_.ye)(c,
this.bc.R(),this.d,this,_.v),this.b._onopen(a))};_.Fe.prototype.tf=function(a){var c=(0,window.String)(this.d),f=(0,_.Ae)(a,"..",c);(0,_.we)(a,this);(0,_.we)(f,this);this.rb("ready",a);this.bc&&this.b._ready&&(a._methods=(0,_.ye)(f,this.bc.R(),c,this,_.v),this.b._ready(a))};_.Fe.prototype.na=function(a){if(this.bc&&this.b._onclose)this.b._onclose(a);else return a=this.rb("close",a),delete _.R.Vc[this.d],a};_.Ge=function(a,c,f,g,h,l,n){_.Ee.call(this,a,c,f,g,_.de,l,n);this.j=h;g._close=this.close;
this.onClosed=this.d;this.T=0;this.dd(function(){this.rb("beforeparentopen");var a=(0,_.we)(this.b);this.Sa._methods=(0,_.ye)(a,"..",this.I,this,_.s);(0,_.re)(this.Sa);var a=(0,_.oe)(this.ja.url,this.Sa,_.v),c=h.Zj(a);this.canAutoClose=function(a){a(h.wi(c))};h.Dk(c,this);this.T=c})};(0,_.De)(_.Ge,_.Ee);_.Ge.prototype.close=function(a){a=this.rb("close",a);this.j.yi(this.T);return a};_.Ge.prototype.d=function(){this.rb("close")};_.He=function(a){return _.R.Ge[a]};_.Ie=function(a,c){_.R.Ge[a]=c};_.Je=
function(a){a=a||{};"auto"===a.height&&(a.height=_.ub.Eg());var c=window&&_.Zd&&_.Zd.ka();c?c.nk(a.width||0,a.height||0):_.Td&&_.Td._resizeMe&&_.Td._resizeMe(a)};_.Ke=function(a){(0,_.se)(a)};_.ae=function(){function a(a){var c=_.v;try{if(a!=_.t)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.Td.id)}catch(n){}try{_.R.wf={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.R.vf.length;++a)_.R.vf[a](_.R.wf);
_.R.vf=[]}catch(r){}}_.R.Vc={};_.R.Ge={};_.R.lg={};_.R.vj=0;_.R.zg=[];_.R.Bf={};_.R.zd={};_.R.wf=_.t;_.R.vf=[];_.Q.L("_noop_echo",function(){var a=_.R.Vc[this.f],c=a&&a.bc,f=_.t;c&&(f={},f.id=c.R(),f.proxyChain=a.yh);this.callback(f)});if(window.parent!=window){var c=_.P.$();c.gcv&&(0,_.se)(c.gcv);var f=c.jsh;f&&(0,_.ue)(f);(0,_.we)((0,_.Ae)(c,"..",""),_.Td);(0,_.we)(c,_.Td);window.setTimeout(function(){_.Q.call("..","_noop_echo",a)},0)}_.R.fa=_.He;_.R.ma=_.Ie;_.R.zk=_.Ke;_.R.gc=_.Je;_.R.Ki=function(a){return _.R.lg[a]};
_.R.Ef=function(a,c){_.R.lg[a]=c};_.R.mk=_.Je;_.R.Kk=_.Ke;_.R.$b={};_.R.$b.get=_.He;_.R.$b.set=_.Ie;_.R.ji=function(a,c){(0,_.xe)(a);_.R.zd[a]=c||window[a]};_.R.Mq=function(a){delete _.R.zd[a]};_.R.open=function(a,c,f,n,r,u){3==arguments.length?n={}:4==arguments.length&&"function"===typeof n&&(r=n,n={});var w="bubble"===c.style&&_.Zd&&_.Zd.ka();return w?new _.Ge(a,c,f,n,w,r,u):(0,_.Be)(c)?new _.Fe(a,c,f,n,r,u):new _.S(a,c,f,n,r,u)};_.R.close=function(a,c){_.Td&&_.Td._close&&_.Td._close(a,c)};_.R.Hb=
function(a,c,f){2==arguments.length&&"function"===typeof r&&(f=c,c={});var n=a||{};"height"in n||(n.height=_.ub.Eg());var r=c||{};n._methods=(0,_.ye)(r,"..","",_.Td,_.s);_.Td&&_.Td._ready&&_.Td._ready(n,f)};_.R.Gg=function(a){_.R.wf?a(_.R.wf):_.R.vf.push(a)};_.R.vi=function(a,c,f){var n=window.Array.prototype.slice.call(arguments);_.R.Gg(function(a){a.sameOrigin&&(n.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.Q.call.apply(_.Q,n))})};_.R.ak=function(a){return!!_.R.Vc[a]};
_.R.Dg=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.J)("googleapis.config/gcv")].join("")};_.R.fk=function(a){var c={mouseover:1,mouseout:1};if(_.Td._event)for(var f=0;f<a.length;f++){var n=a[f];n in c&&_.P.Wd(window.document,n,function(a){_.Td._event({event:a.type,timestamp:(new window.Date).getTime()})},_.s)}};_.R.Bk=_.ue;_.R.Df=_.ve;_.R.Do=_.pe;_.R.xj=_.Td};(0,_.ae)()}else _.R.ji=_.R.allow,_.R.vi=_.R.callSiblingOpener,_.R.close=_.R.close,_.R.Dg=_.R.getGoogleConnectJsUri,_.R.fa=_.R.getHandler,
_.R.Ki=_.R.getDeferredHandler,_.R.Gg=_.R.getParentInfo,_.R.xj=_.R.iframer,_.R.open=_.R.open,_.R.ak=_.R.openedId_,_.R.fk=_.R.propagate,_.R.Hb=_.R.ready,_.R.gc=_.R.resize,_.R.zk=_.R.setGoogleConnectJsVersion,_.R.Bk=_.R.setJsHint,_.R.Df=_.R.setBootstrapHint,_.R.ma=_.R.setHandler,_.R.Ef=_.R.setDeferredHandler,_.Ee=window.IframeBase,_.Ee.prototype=window.IframeBase.prototype,_.A=_.Ee.prototype,_.A.ea=_.Ee.prototype.addCallback,_.A.Vb=_.Ee.prototype.getMethods,_.A.Aa=_.Ee.prototype.getOpenerIframe,_.A.ga=
_.Ee.prototype.getOpenParams,_.A.Pa=_.Ee.prototype.getParams,_.A.Ib=_.Ee.prototype.removeCallback,_.S=window.Iframe,_.S.prototype=window.Iframe.prototype,_.A=_.S.prototype,_.A.close=_.S.prototype.close,_.A.Ua=_.S.prototype.exposeMethod,_.A.R=_.S.prototype.getId,_.A.X=_.S.prototype.getIframeEl,_.A.S=_.S.prototype.getSiteEl,_.A.Na=_.S.prototype.openInto,_.A.remove=_.S.prototype.remove,_.A.Lb=_.S.prototype.setSiteEl,_.A.ea=_.S.prototype.addCallback,_.A.Vb=_.S.prototype.getMethods,_.A.Aa=_.S.prototype.getOpenerIframe,
_.A.ga=_.S.prototype.getOpenParams,_.A.Pa=_.S.prototype.getParams,_.A.Ib=_.S.prototype.removeCallback,_.Fe=window.IframeProxy,_.Fe.prototype=window.IframeProxy.prototype,_.A=_.Fe.prototype,_.A.Mi=_.Fe.prototype.getTargetIframeId,_.A.ea=_.Fe.prototype.addCallback,_.A.Vb=_.Fe.prototype.getMethods,_.A.Aa=_.Fe.prototype.getOpenerIframe,_.A.ga=_.Fe.prototype.getOpenParams,_.A.Pa=_.Fe.prototype.getParams,_.A.Ib=_.Fe.prototype.removeCallback,window.IframeWindow&&(_.Ge=window.IframeWindow,_.Ge.prototype= window.IframeWindow.prototype,_.Ge.prototype.close=_.Ge.prototype.close,_.Ge.prototype.d=_.Ge.prototype.onClosed),_.R.$b=window.iframes.handlers,_.R.$b.get=_.R.$b.get,_.R.$b.set=_.R.$b.set,_.R.mk=_.R.resizeMe,_.R.Kk=_.R.setVersionOverride;
(0,_.N)("iframes.allow",_.R.ji);(0,_.N)("iframes.callSiblingOpener",_.R.vi);(0,_.N)("iframes.close",_.R.close);(0,_.N)("iframes.getGoogleConnectJsUri",_.R.Dg);(0,_.N)("iframes.getHandler",_.R.fa);(0,_.N)("iframes.getDeferredHandler",_.R.Ki);(0,_.N)("iframes.getParentInfo",_.R.Gg);(0,_.N)("iframes.iframer",_.R.xj);(0,_.N)("iframes.open",_.R.open);(0,_.N)("iframes.openedId_",_.R.ak);(0,_.N)("iframes.propagate",_.R.fk);(0,_.N)("iframes.ready",_.R.Hb);(0,_.N)("iframes.resize",_.R.gc);
(0,_.N)("iframes.setGoogleConnectJsVersion",_.R.zk);(0,_.N)("iframes.setBootstrapHint",_.R.Df);(0,_.N)("iframes.setJsHint",_.R.Bk);(0,_.N)("iframes.setHandler",_.R.ma);(0,_.N)("iframes.setDeferredHandler",_.R.Ef);(0,_.N)("IframeBase",_.Ee);(0,_.N)("IframeBase.prototype.addCallback",_.Ee.prototype.ea);(0,_.N)("IframeBase.prototype.getMethods",_.Ee.prototype.Vb);(0,_.N)("IframeBase.prototype.getOpenerIframe",_.Ee.prototype.Aa);(0,_.N)("IframeBase.prototype.getOpenParams",_.Ee.prototype.ga);
(0,_.N)("IframeBase.prototype.getParams",_.Ee.prototype.Pa);(0,_.N)("IframeBase.prototype.removeCallback",_.Ee.prototype.Ib);(0,_.N)("Iframe",_.S);(0,_.N)("Iframe.prototype.close",_.S.prototype.close);(0,_.N)("Iframe.prototype.exposeMethod",_.S.prototype.Ua);(0,_.N)("Iframe.prototype.getId",_.S.prototype.R);(0,_.N)("Iframe.prototype.getIframeEl",_.S.prototype.X);(0,_.N)("Iframe.prototype.getSiteEl",_.S.prototype.S);(0,_.N)("Iframe.prototype.openInto",_.S.prototype.Na);
(0,_.N)("Iframe.prototype.remove",_.S.prototype.remove);(0,_.N)("Iframe.prototype.setSiteEl",_.S.prototype.Lb);(0,_.N)("Iframe.prototype.addCallback",_.S.prototype.ea);(0,_.N)("Iframe.prototype.getMethods",_.S.prototype.Vb);(0,_.N)("Iframe.prototype.getOpenerIframe",_.S.prototype.Aa);(0,_.N)("Iframe.prototype.getOpenParams",_.S.prototype.ga);(0,_.N)("Iframe.prototype.getParams",_.S.prototype.Pa);(0,_.N)("Iframe.prototype.removeCallback",_.S.prototype.Ib);(0,_.N)("IframeProxy",_.Fe);
(0,_.N)("IframeProxy.prototype.getTargetIframeId",_.Fe.prototype.Mi);(0,_.N)("IframeProxy.prototype.addCallback",_.Fe.prototype.ea);(0,_.N)("IframeProxy.prototype.getMethods",_.Fe.prototype.Vb);(0,_.N)("IframeProxy.prototype.getOpenerIframe",_.Fe.prototype.Aa);(0,_.N)("IframeProxy.prototype.getOpenParams",_.Fe.prototype.ga);(0,_.N)("IframeProxy.prototype.getParams",_.Fe.prototype.Pa);(0,_.N)("IframeProxy.prototype.removeCallback",_.Fe.prototype.Ib);(0,_.N)("IframeWindow",_.Ge);
(0,_.N)("IframeWindow.prototype.close",_.Ge.prototype.close);(0,_.N)("IframeWindow.prototype.onClosed",_.Ge.prototype.d);(0,_.N)("iframes.util.getTopMostAccessibleWindow",_.R.F.uc);(0,_.N)("iframes.handlers.get",_.R.$b.get);(0,_.N)("iframes.handlers.set",_.R.$b.set);(0,_.N)("iframes.resizeMe",_.R.mk);(0,_.N)("iframes.setVersionOverride",_.R.Kk);

}catch(e){_._DumpException(e)}
try{
_.Le=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};_.Me=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.Ne=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.X(),h=g.parentNode,l=f.width,f=f.height;(0,_.Le)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";l&&(g.width=l+"px");f&&(g.height=f+"px");(l=c?c.title:_.t)&&a.X().setAttribute("title",l)};
_.Oe={open:function(a){var c=window.document.getElementById(a.ga().container);return a.Na(c,{style:(0,_.Me)(c,a)})},attach:function(a,c){var f=window.document.getElementById(a.ga().container);a.wm(c);a.vm({style:(0,_.Me)(f,a)})}};_.Oe.onready=_.Ne;_.Oe.onRenderStart=_.Ne;_.Oe.close=function(a){var c=a.S();c&&c.removeChild(a.X())};_.R.ma("inline",_.Oe);

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Pe=function(a,c){this.b=a;this.nc=c};_.Qe=function(a){this.w=this.Rb=a;this.n=_.t;this.slf=0;this.ssh=_.v;this.sen=_.s;this.shl=this.itm=_.t};_.Pe.prototype.j=function(a){this.b.or(this.nc,a)};_.Pe.prototype.I=function(){this.b.oc(this.nc)};_.Qe.prototype.sm=function(a,c){this.Rb.xk(new _.Pe(a,this));this.n=c};_.Qe.prototype.sh=function(){this.Rb.show()};_.Qe.prototype.hi=function(){this.Rb.rj()};_.Qe.prototype.cl=function(){this.Rb.close()};_.Qe.prototype.en=function(){this.Rb.enable()};_.Qe.prototype.di=function(){this.Rb.disable()};_.Qe.prototype.hl=function(a){this.Rb.jn(a)};_.Qe.prototype.vr=function(a,c){this.Rb.Oi(a,c)};

}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.Re=function(a){this.nc=a;this.Ma=0;this.Ee=_.v;this.Di=_.s;this.He=_.t};_.Se=function(a){return 5==a.Ma||4==a.Ma};
_.Te=function(a,c,f){this.d=a||{};this.i=c||0;this.j=f||0;a={};c=(0,_.D)(this.Bg,this);a.fc=c;c=(0,_.D)(this.Af,this);a.rc=c;c=(0,_.D)(this.Gf,this);a.sc=c;c=(0,_.D)(this.se,this);a.hc=c;c=(0,_.D)(this.Zd,this);a.cc=c;c=(0,_.D)(this.mj,this);a.os=c;c=(0,_.D)(this.lj,this);a.or=c;c=(0,_.D)(this.jj,this);a.oh=c;c=(0,_.D)(this.hj,this);a.oc=c;c=(0,_.D)(this.ij,this);a.oe=c;c=(0,_.D)(this.kj,this);a.oi=c;this.b=a};
_.Ue=function(a,c){var f=a.j-a.i;0<f&&(f=(0,window.setTimeout)((0,_.D)(function(){(0,_.Se)(c)||(c.Ma=4,this.Zd(c.qc()))},a),f),c.He=f)};_.Ve=function(a,c){c.He!=_.t&&((0,window.clearTimeout)(c.He),c.He=_.t)};_.We=function(a,c){(0,_.Ve)(a,c);c.Ma=5;var f=a.d,g;for(g in f)f[g]==c&&delete f[g]};_.Xe=function(a,c){return a.d[c.n]};_.Ye=function(a){this.b=a};_.Ze=function(){_.Te.call(this)};
_.$e=function(a){if(window.___jsl.man)a(window.___jsl.man);else if(window.gbar){var c=function(){var c=new _.Ye(window.gbar.wg);window.___jsl.man=c;a(c)};window.gbar.wg?c():window.gbar.qm(c)}else c=new _.Ze,window.___jsl.man=c,a(c)};_.af=function(){return window.___jsl.man};_.Re.prototype.qc=(0,_.z)("nc");_.Re.prototype.isEnabled=(0,_.z)("Di");_.Re.prototype.la=(0,_.ba)("Di");
_.A=_.Te.prototype;_.A.Af=function(a,c,f){try{a=a+(c!=_.t?"_"+c:""),f.sm(this.b,a),this.d[a]=new _.Re(f)}catch(g){return _.v}return _.s};_.A.Bg=function(a,c){var f=this.d[a+(c!=_.t?"_"+c:"")];return f?f.qc():_.t};_.A.Gf=function(a){var c=(0,_.Xe)(this,a);if(c&&(2==c.Ma||3==c.Ma)&&c.isEnabled()&&!c.Ee){try{a.sh()}catch(f){}c.Ee=_.s}};_.A.se=function(a){var c=(0,_.Xe)(this,a);if(c&&(2==c.Ma||3==c.Ma||(0,_.Se)(c))&&c.Ee){try{a.hi()}catch(f){}c.Ee=_.v}};
_.A.Zd=function(a){var c=(0,_.Xe)(this,a);if(c&&5!=c.Ma){try{this.se(a),a.cl()}catch(f){}(0,_.We)(this,c)}};_.A.mj=function(a){var c=(0,_.Xe)(this,a);c&&0==c.Ma&&(this.i?(a=(0,window.setTimeout)((0,_.D)(function(){(0,_.Se)(c)||(0,_.Ue)(this,c)},this),this.i),c.He=a):(0,_.Ue)(this,c),c.Ma=1)};_.A.lj=function(a){if((a=(0,_.Xe)(this,a))&&!(0,_.Se)(a)&&1==a.Ma)(0,_.Ve)(this,a),a.Ma=3};_.A.jj=function(a){if((a=(0,_.Xe)(this,a))&&!(0,_.Se)(a))a.Ee=_.v};
_.A.hj=function(a){var c=(0,_.Xe)(this,a);if(c&&!(0,_.Se)(c)){try{this.se(a)}catch(f){}(0,_.We)(this,c)}};_.A.ij=function(a){if((a=(0,_.Xe)(this,a))&&!(0,_.Se)(a))a.Ma=4,this.Zd(a.qc())};_.A.kj=function(a,c){var f=(0,_.Xe)(this,a);f&&!(0,_.Se)(f)&&(2<=c&&4>=c&&!(0,_.Se)(f))&&((0,_.Ve)(this,f),f.Ma=2)};
_.A=_.Ye.prototype;_.A.Af=function(a,c,f){return this.b.rc(a,c,f)};_.A.Bg=function(a,c){return this.b.fc(a,c)};_.A.Gf=function(a){this.b.sc(a)};_.A.se=function(a){this.b.hc(a)};_.A.Zd=function(a){this.b.cc(a)};_.A.mj=function(a){this.b.os(a)};_.A.lj=function(a,c){this.b.or(a,c)};_.A.jj=function(a){this.b.oh(a)};_.A.hj=function(a){this.b.oc(a)};_.A.ij=function(a,c,f,g,h,l){this.b.oe(a,c,f,g,h,l)};_.A.kj=function(a,c,f,g){this.b.oi(a,c,f,g)};
(0,_.E)(_.Ze,_.Te);
}catch(e){_._DumpException(e)}
try{
_.bf=function(a){var c=window.document.createElement("div"),f=window.document.createElement("a");f.href=a;c.appendChild(f);c.innerHTML=c.innerHTML;return c.firstChild.href};_.cf=function(a){for(var a=a||"canonical",c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href")))if(h=(0,_.bf)(h))return h}return window.location.href};_.df=function(a,c,f,g){return a?(0,_.bf)(a):(0,_.cf)(g)};
_.ef=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.ff=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.gf=function(a){if((0,_.ef)(a))return"true"};_.hf=function(a){return"string"==typeof a&&_.jf[a.toLowerCase()]?a.toLowerCase():"standard"};_.kf=function(a,c){return"tall"==(0,_.hf)(c)?"true":a==_.t||(0,_.ef)(a)?"true":"false"};_.lf=function(a,c,f){a==_.t&&f&&(a=f.db,a==_.t&&(a=f.gwidget&&f.gwidget.db));return a||_.q};
_.mf=function(a,c,f){a==_.t&&f&&(a=f.ecp,a==_.t&&(a=f.gwidget&&f.gwidget.ecp));return a||_.q};_.jf={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.nf={href:[_.df,"url"],width:[_.ff],size:[_.hf],resize:[_.gf],autosize:[_.gf],count:[function(a,c){return(0,_.kf)(c.count,c.size)}],db:[_.lf],ecp:[_.mf],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.gf],recommendations:[],fu:[],ad:[_.gf],cr:[_.ff],ag:[_.ff],"fr-ai":[],"fr-sigh":[]};

}catch(e){_._DumpException(e)}
try{
_.of=function(a,c,f){var g;try{g=a.createElement('<iframe frameborder="'+(0,_.sa)(f.frameborder)+'" scrolling="'+(0,_.sa)(f.scrolling)+'" name="'+(0,_.sa)(f.name)+'"/>')}catch(h){g=a.createElement("iframe")}for(var l in f)a=f[l],"style"==l&&"object"===typeof a?(0,_.Ba)(a,g.style):g.setAttribute(l,f[l]);(0,_.Ka)(c);c.appendChild(g);f.allowtransparency&&(g.allowTransparency=_.s);return g};
_.pf=function(a,c,f){var f=f||{},g=c.ownerDocument,h,l=0;do h=f.id||["I",_.qf++,"_",(new window.Date).getTime()].join("");while(g.getElementById(h)&&5>++l);(0,_.Ca)(5>l,"Error creating iframe id");var n=g.location.href,l=(0,_.ya)(),r=(0,_.Oa)(n);r&&(l._bsh=r);(n=(0,_.La)(n))&&(l.jsh=n);var u,n=(0,_.ya)();n.id=h;n.parent=g.location.protocol+"//"+g.location.host;var r=(0,_.Da)(g.location.href,"id",""),w=(0,_.Da)(g.location.href,"pfname","");(r=r?w+"/"+r:"")&&(n.pfname=r);f.hintInFragment?(0,_.Ba)(l,
n):u=l;a=(0,_.Ja)(a,u,n);u=(0,_.ya)();(0,_.Ba)(_.rf,u);u.name=u.id=h;(0,_.Ba)(f.attributes,u);u.src=a;return(0,_.of)(g,c,u,a,h,f)};_.rf={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.qf=0;

}catch(e){_._DumpException(e)}
try{
_.sf=function(a,c,f,g){_.tf[f]=_.tf[f]||!!g;(0,_.qa)(_.uf,f,[]);_.uf[f].push([a,c])};_.vf=function(a,c){var f=(0,_.qa)(_.wf,a,(0,_.ya)());return(0,_.qa)(f,c,(0,_.ya)())};_.xf=function(a,c,f){var g=_.t;c&&f&&(g=(0,_.vf)(c,f)[a]);return g||_.yf[a]};_.zf=function(a){this.t={};this.tick=function(a,f,g){this.t[a]=[g!=_.q?g:(new window.Date).getTime(),f]};this.tick("start",_.t,a)};_.Af=function(a,c){this.type=!a?"g":"_p"==a?"m":"w";this.name=a;this.b=c};
_.Bf=function(a){var c=[];c.push("l"+((0,_.J)("isPlusUser")?"1":"0"));var f="m"+(_.Cf?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.b);else if("w"==a.type){var g="n"+a.b;c.push(g);"0"==a.b&&c.push(f+g)}return c};_.Df=function(a,c,f){for(var g=new _.Af(c,f),h=(0,_.qa)(_.Ef,g.key(),(0,_.ya)()),l=_.uf[a]||[],n=0;n<l.length;++n){var r=l[n],u=h,w=r[0],y=a,C=c,G=f,r=(0,_.xf)(r[1],C,G),y=(0,_.xf)(y,C,G);u[w]=r&&y?y-r:_.t}_.tf[a]&&_.Ff&&((0,_.If)(_.Jf),(0,_.If)(g))};
_.Kf=function(a,c){for(var c=c||[],f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.If=function(a){var c=_.Ya.__gapi_jstiming__;c.sn=_.Lf[a.type];var f=new c.Timer(0),g;a:{switch(a.type){case "g":g="global";break a;case "m":g=a.b;break a;case "w":g=a.name;break a}g=_.q}f.name=g;g=_.v;var h=a.key(),l=_.Ef[h];f.tick("_start",_.t,0);for(var n in l)f.tick(n,"_start",l[n]),g=_.s;_.Ef[h]=(0,_.ya)();if(g){n=[];g=(0,_.J)("lexps");n=n.concat((0,_.Kf)("e",g));n=n.concat((0,_.Kf)("",(0,_.Bf)(a)));for(h=0;h<_.Mf.length;h++)l=_.Mf[h],0<=_.ra.call(g,l)&&(n=n.concat((0,_.Kf)(l?"e"+l:"",(0,_.Bf)(a)))); n=(0,_.Kf)("abc_",n);c.report(f,{e:n.join(",")})}};_.Nf=(0,_.qa)(_.Ma,"perf",(0,_.ya)());_.yf=(0,_.qa)(_.Nf,"g",(0,_.ya)());_.wf=(0,_.qa)(_.Nf,"i",(0,_.ya)());(0,_.qa)(_.Nf,"r",[]);_.tf=(0,_.ya)();_.uf=(0,_.ya)();
_.Of=new _.zf;window.__gapi_jstiming__={Timer:_.zf,load:_.Of};if(window.performance&&window.performance.timing){_.Pf=window.performance.timing;_.Qf=window.__gapi_jstiming__.load;_.Rf=_.Pf.navigationStart;_.Sf=_.Pf.responseStart;0<_.Rf&&_.Sf>=_.Rf&&(_.Qf.tick("_wtsrt",_.q,_.Rf),_.Qf.tick("wtsrt_","_wtsrt",_.Sf),_.Qf.tick("tbsd_","wtsrt_"))}
try{_.Tf=_.t;window.chrome&&window.chrome.csi&&(_.Tf=window.Math.floor(window.chrome.csi().pageT),_.Qf&&0<_.Rf&&(_.Qf.tick("_tbnd",_.q,window.chrome.csi().startE),_.Qf.tick("tbnd_","_tbnd",_.Rf)));_.Tf==_.t&&window.gtbExternal&&(_.Tf=window.gtbExternal.pageT());_.Tf==_.t&&window.external&&(_.Tf=window.external.pageT,_.Qf&&0<_.Rf&&(_.Qf.tick("_tbnd",_.q,window.external.startE),_.Qf.tick("tbnd_","_tbnd",_.Rf)));_.Tf&&(window.__gapi_jstiming__.pt=_.Tf)}catch(Uf){};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.ti={};window.__gapi_jstiming__.hp=1;_.Vf=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.q?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.Vf;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.Wf=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var l=window.chrome;if(l&&(l=l.loadTimes)){l().wasFetchedViaSpdy&&(g+="&p=s");if(l().wasNpnNegotiated){var g=g+"&npn=1",n=l().npnNegotiatedProtocol;n&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(n))}l().wasAlternateProtocolAvailable&&(g+="&apa=1")}var r=a.t,u=r.start,l=[],n=[],w;for(w in r)if("start"!=w&&0!=w.indexOf("_")){var y=r[w][1];y?r[y]&&
n.push(w+"."+(0,_.Vf)(a,w,r[y][0])):u&&l.push(w+"."+(0,_.Vf)(a,w))}if(c)for(var C in c)g+="&"+C+"="+c[C];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,n.length?"&it="+n.join(","):"","",g,"&rt=",l.join(",")].join("");if(!a)return"";var g=new window.Image,G=window.__gapi_jstiming__.hp++;window.__gapi_jstiming__.ti[G]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.ti[G]};g.src=a;g=_.t;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.v,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var l;"prerender"==window.document.webkitVisibilityState?l=_.v:((0,_.Wf)(a,c,f),l=_.s);l&&(g=_.s,window.document.removeEventListener("webkitvisibilitychange",h,_.v))}};window.document.addEventListener("webkitvisibilitychange",h,_.v);return""}return(0,_.Wf)(a,c,f)}};
_.Mf=[73,74,77,78];_.Lf={g:"gapi_global",m:"gapi_module",w:"gwidget"};_.Af.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.b;case "w":return this.type+"."+this.name+this.b}};_.Jf=new _.Af;_.Cf=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.Ef=(0,_.qa)(_.Nf,"_c",(0,_.ya)());_.Ff=window.Math.random()<((0,_.J)("csi/rate")||0);(0,_.sf)("blt","bs0","bs1");(0,_.sf)("psi","ps0","ps1");(0,_.sf)("rpcqi","rqe","rqd");
(0,_.sf)("mli","ml0","ml1");(0,_.sf)("mei","me0","me1",_.s);(0,_.sf)("wci","wrs","wdc");(0,_.sf)("wdi","wrs","wrdi");(0,_.sf)("wdt","bs0","wrdt");(0,_.sf)("wri","wrs","wrri",_.s);(0,_.sf)("wrt","bs0","wrrt");(0,_.sf)("wji","wje0","wje1",_.s);(0,_.sf)("wjli","wjl0","wjl1");(0,_.sf)("whi","wh0","wh1",_.s);_.Xf=_.Nf.r;if("function"!==typeof _.Xf){for(_.Yf;_.Yf=_.Xf.shift();)_.Df.apply(_.t,_.Yf);_.Nf.r=_.Df};

}catch(e){_._DumpException(e)}
try{
_.Zf=function(){return(new window.Date).getTime()};_.$f=function(a,c,f){var g=_.Nf.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};_.ag=function(a,c){if("string"==typeof a){var f;for(f=0;f<c.length;f++)if(c[f]==a.toLowerCase())return a.toLowerCase()}};_.bg=function(a,c,f,g){"_p"==c&&(0,_.m)((0,window.Error)("l`_p"));(0,_.vf)(c,f)[a]=g||(0,_.Zf)();(0,_.$f)(a,c,f)};_.cg=function(a){return(0,_.ag)(a,_.dg)};_.eg=function(a){return(0,_.ag)(a,_.fg)};
_.gg=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};_.hg=function(a){a.source=[_.t,"source"];a.expandTo=[_.t,"expandTo"];a.align=[_.eg];a.annotation=[_.cg];a.origin=[_.gg]};_.ig=function(a,c,f){return(0,_.df)(a,c,f,c.action?_.t:"publisher")};_.jg=function(a,c){if(!_.kg){var f=(0,_.J)("iframes/:socialhost:"),g=(0,_.Ud)(_.q)||"0",h=(0,_.Ud)(_.q);_.kg={socialhost:f,session_index:g,session_prefix:h!==_.q&&h!==_.t&&""!==h?"u/"+h+"/":""}}return _.kg[c]||""};
_.lg=function(a,c,f,g){if(!c.parentNode)return _.t;if(!g){for(var g=(0,_.ya)(),h=0!=c.nodeName.toLowerCase().indexOf("g:"),l=0,n=c.attributes.length;l<n;l++){var r=c.attributes[l],u=r.name,r=r.value;0<=_.ra.call(_.mg,u)||(h&&0!=u.indexOf("data-")||"null"===r)||(h&&(u=u.substr(5)),g[u.toLowerCase()]=r)}h=c.style;(l=(0,_.ng)(h&&h.height))&&(g.height=(0,window.String)(l));(h=(0,_.ng)(h&&h.width))&&(g.width=(0,window.String)(h))}h=a;"plus"==a&&g.action&&(h=a+"_"+g.action);(h=(0,_.J)("iframes/"+h+"/url"))||
(h=":socialhost:/_/widget/render/"+a);h=h.replace(_.og,_.jg);l={};(0,_.Ba)(g,l);l.hl=(0,_.J)("lang")||"en-US";l.origin=(0,_.gg)();"plus"===a&&(l.url=(0,_.ig)(l.href,g,_.t),delete l.href);"plusone"===a&&(l.url=g.href?(0,_.bf)(g.href):(0,_.cf)(),l.db=(0,_.lf)(g.db,_.q,(0,_.J)()),l.ecp=(0,_.mf)(g.ecp,_.q,(0,_.J)()),delete l.href);l.hl=(0,_.J)("lang")||"en-US";_.Ma.ILI&&(l.iloader="1");delete l["data-onload"];delete l.rd;n=(0,_.J)("inline/css");"undefined"!==typeof n&&(0<f&&n>=f)&&(l.ic="1");var n=/^#|^fr-/,
f={},w;for(w in l)(0,_.Aa)(l,w)&&n.test(w)&&(f[w.replace(n,"")]=l[w],delete l[w]);w=[].concat(_.pg);n=(0,_.J)("iframes/"+a+"/methods");"object"===typeof n&&_.za.test(n.push)&&(w=w.concat(n));for(var y in g)if((0,_.Aa)(g,y)&&/^on/.test(y)&&("plus"!=a||"onconnect"!=y))w.push(y),delete l[y];f._methods=w.join(",");h=(0,_.Ja)(h,l,f);g.rd?y=c:(y=window.document.createElement("div"),c.setAttribute("data-gapistub",_.s),y.style.cssText="position:absolute;width:100px;left:-10000px;",c.parentNode.insertBefore(y,
c));y.id||(c=y,(0,_.qa)(_.qg,a,0),w="___"+a+"_"+_.qg[a]++,c.id=w);c=(0,_.ya)();c[">type"]=a;(0,_.Ba)(g,c);y.setAttribute("data-gwattr",(0,_.Ia)(c).join(":"));a=(0,_.pf)(h,y,{attributes:_.rg});c={};c.userParams=g;c.url=h;c.iframeNode=a;c.id=a.getAttribute("id");return c};_.ng=function(a){var c=_.q;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};
_.sg=function(a,c){_.yf.ps0=(0,_.Zf)();(0,_.$f)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.Za,g,h=_.Za.documentMode;if(f.querySelectorAll&&(!h||8<h)){if(c)g=[c];else if(_.za.test(window.Object.keys))g=window.Object.keys(_.tg);else{h=[];for(g in _.tg)(0,_.Aa)(_.tg,g)&&h.push(g);g=h}for(var h=[],l=0;l<g.length;l++){var n=g[l];h.push(".g-"+n,"g\\:"+n)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.ya)();for(h=0;h<g.length;h++){l=g[h];var r=
l,n=c,u=r.nodeName.toLowerCase(),w=_.q;r.getAttribute("data-gapiscan")?n=_.t:(0==u.indexOf("g:")?w=u.substr(2):(r=(r=(0,window.String)(r.className||r.getAttribute("class")))&&_.ug.exec(r))&&(w=r[1]),n=w&&_.tg[w]&&(!n||w===n)?w:_.t);n&&(l.setAttribute("data-gapiscan",_.s),(0,_.qa)(f,n,[]).push(l))}for(var y in f)_.vg.push(y);_.yf.ps1=(0,_.Zf)();(0,_.$f)("ps1");_.$a.load(_.vg.join(":"),_.q);var C;y=[];for(C in f){g=f[C];h=0;for(l=g.length;h<l;h++)if(n=(0,_.lg)(C,g[h],l))(w=n.id)&&y.push(w),(0,_.wg)(C,
n)}};_.wg=function(a,c){var f=(0,_.qa)(_.Ma,"watt",(0,_.ya)())[a];c&&f?f(c):_.$a.load(a,function(){var f=(0,_.qa)(_.Ma,"watt",(0,_.ya)())[a],h=c&&c.iframeNode;!h||!f?(0,_.$a[a].go)(h&&h.parentNode):f(c)})};_.xg=function(a){var c=(0,_.J)(a);return"undefined"!==typeof c?c:(0,_.J)("gwidget/"+a)};_.yg=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};
_.zg=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.t};_.Ag=function(a){return a.Op&&window.gbar&&window.gapi.load};_.Bg=function(a,c,f,g){return _.R.open(a,c,f,g)};_.Cg=function(a,c){for(var f in _.Dg)if(_.Dg.hasOwnProperty(f)){var g=_.Dg[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};_.Eg=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.Fg)(c[g],c,_.Gg));return f};
_.Hg=function(a,c,f,g){var h=(0,_.Eg)(a.ja,f);a.kk.push({element:c,ja:h,Hd:(0,_.Cg)(h,(0,_.Eg)(a.ck,f)),Kd:g,Lm:!!f["data-onload"]})};_.Ig=function(a){function c(){for(var c=a.kk,g=a.xh;0<c.length;)g(c.shift())}(0,_.Ag)(a)?(0,_.$e)(c):c()};_.Fg=function(a){return a};_.Jg=function(){};_.Kg=function(a){this.d=a;this.b=_.t};_.dg="inline bubble none only pp vertical-bubble".split(" ");_.fg=["left","right"];_.Lg={};
_.og=/:([a-zA-Z_]+):/g;_.rg={style:"position:absolute;top:-10000px;width:300px;margin:0px;borderStyle:none"};_.pg="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.kg=_.t;_.qg=(0,_.qa)(_.Ma,"WI",(0,_.ya)());_.mg=["style","data-gapiscan"];
_.ug=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.tg=(0,_.ya)();_.vg=(0,_.qa)(_.Ma,"FW",[]);(0,_.qa)(_.$a,"platform",{}).go=_.sg;_.Ng=["div"];_.Og="onload";_.Pg=_.s;_.Gg=_.t;_.Gg=(0,_.J)();(0,_.J)("gwidget");_.Qg=(0,_.xg)("parsetags");_.Og="explicit"===_.Qg||"onload"===_.Qg?_.Qg:_.Og;_.Rg=(0,_.xg)("google_analytics");"undefined"!==typeof _.Rg&&(_.Pg=!!_.Rg);_.Sg={};_.Sg.width=[(0,_.yg)(450)];_.Sg.height=[(0,_.yg)(24)];_.Sg.callback=[_.zg];_.Sg.onready=[_.zg];_.Sg.lang=[function(){return(0,_.xg)("lang")||"en-US"},"hl"];_.Sg.iloader=[function(){return _.Ma.ILI},"iloader"];_.Dg=_.Sg;
_.Mg={ub:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[l.al]=1;l.nh=c}function f(){"onload"===_.Og&&u.go()}function g(a){var c=a.userParams;if((a=(a=a.iframeNode)&&a.parentNode)&&1===a.nodeType)a.removeAttribute("data-gwattr"),(0,_.Hg)(h,a,c,3);(0,_.Ig)(h)}var h,l={};l.Ta=a[0];l.Lf=-1;l.$k="___"+l.Ta+"_";l.al="g:"+l.Ta;l.oo="g-"+l.Ta;l.kk=[];l.ja={};l.dg=[];l.sg=[];a[1]&&(l.ck=a[1]);l.ja=a[2]||{};for(var n in _.Dg)_.Dg.hasOwnProperty(n)&&!l.ja.hasOwnProperty(n)&&
(l.ja[n]=_.Dg[n]);a[3]&&(l.dg=a[3]);a[4]&&c(a[4]);a[5]&&(l.Jd=a[5]);l.Op=a[7]===_.s;l.$o=a[8];l.nh||c(_.Ng);if(a=a[6])if("number"==typeof a.length){l.sg=a;for(var r=a.length-1;0<=r;--r)l.ja[a[r]]=[_.zg]}else for(r in a)a.hasOwnProperty(r)&&!l.ja.hasOwnProperty(r)&&(l.sg.push(r),l.ja[r]=a[r]);l.xh=function(a){function c(){tq||(tq=_.s,f(),uq&&(0,_.bg)("wrrt",hc,ic),(0,_.bg)("wrri",hc,ic))}function f(){vq||(vq=_.s,Kb.X(),uq&&(0,_.bg)("wrdt",hc,ic),(0,_.bg)("wrdi",hc,ic))}function g(a){var a=a||Kb,c=
Kb.Ye(a.width);c&&zh.style.width!=c.Mc&&(zh.style.width=c.Mc);if((a=Kb.Ye(a.height))&&zh.style.height!=a.Mc)zh.style.height=a.Mc}l.Lf++;(0,_.bg)("wrs",l.Ta,(0,window.String)(l.Lf));var h=[];l.Jd&&(h[0]=a.element,h[1]=a.Kd,l.Jd("s",h),a.Kd=h[1]);var n=a.element,r=n.parentNode,u=a.ja;if(0===a.Kd){var w=window.document.createElement("div");r.insertBefore(w,n);r.removeChild(n);n=w}w=n.style;if(n.id){if(3===a.Kd&&0===n.id.indexOf(l.$k)){var V=n.nextSibling;V&&(V.getAttribute&&V.getAttribute("data-gapistub"))&&
r.removeChild(V);w.cssText=""}}else{var r=n,V=l.$k,oa=l.Ta,Na=(0,_.qa)(_.Ma,"WI",(0,_.ya)());window.Object.prototype.hasOwnProperty.call(Na,oa)||(Na[oa]=0);var ib=Na[oa];Na[oa]=ib+1;r.id=V+ib}u.height&&(w.height=u.height+"px");u.width&&(w.width=u.width+"px");w.display||(w.display="inline-block");(0,_.Ag)(l)&&(w.display="none");(0,_.Le)(n);var Ea=":"+l.Ta;":plus"==Ea&&(a.Hd&&a.Hd.action)&&(Ea+="_"+a.Hd.action);var w={},r=l.dg[0],V=u.callback,Ah=l.dg[1];if(Ah&&_.Pg)var Zx=V||(0,_.x)(),V=function(a){var c=
Ah(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.t):window._gaq&&window._gaq.push(["_trackSocial","Google",c,a.href||_.t])}catch(g){}Zx(a)};r&&V&&(w[r]=V);r=l.sg;for(V=r.length-1;0<=V;--V){var wb=r[V];(oa=u[wb])&&(w[wb]=oa)}r={};for(wb in a.Hd)a.Hd[wb]!=_.t&&(r[wb]=a.Hd[wb]);wb={container:n.id,style:"inline",height:u.height,width:u.width};if(3===a.Kd){if(!_.R.fa("attach")){var Yd={},Gf=_.R.fa("inline"),Uc;for(Uc in Gf)Gf.hasOwnProperty(Uc)&&
(Yd[Uc]=Gf[Uc]);Yd.open=function(a){var c;a:{c=window.document.getElementById(a.ga().container).getElementsByTagName("IFRAME");for(var f=0;f<c.length;++f){var g=c[f];if(g.id&&/^I\d+_\d+$/.test(g.id)){c=g;break a}}c=_.q}return c?Gf.attach(a,c):Gf.open(a)};_.R.ma("attach",Yd)}wb.style="attach"}else if((0,_.Ag)(l)){wb._ct=l.Ta;wb._ci=l.Lf;if(!_.R.fa("inline-managed")){Uc={};var Hf=_.R.fa("inline");for(Yd in Hf)Hf.hasOwnProperty(Yd)&&(Uc[Yd]=Hf[Yd]);Uc.open=function(a){Hf.open(a);var c=new _.Qe(new _.Kg(a));
(0,_.af)().Af(a.ga()._ct,a.ga()._ci,c)&&(a=c[_.Lg.wl.Bl],a.b&&(a=a.b,a.b.os(a.nc)))};Uc.onready=function(a){Hf.onready(a);var c=(0,_.af)();if(a=c.Bg(a.ga()._ct,a.ga()._ci)){var f=a[_.Lg.wl.Bl];f.b&&f.b.j({});c.Gf(a)}};_.R.ma("inline-managed",Uc)}wb.style="inline-managed"}l.Jd&&(h[2]=wb,h[3]=r,h[4]=w,l.Jd("i",h),a.Kd=h[1]);var Kb=function(a){var c=_.Bg.apply(_.t,[Ea].concat([].slice.call(arguments,0)));if(u.onready){var f=_.v,g=function(){f||(f=_.s,u.onready.call(_.t))};c.ea("ready",g);c.ea("renderstart",
g)}(0,_.Jg)(c);return c}(wb,r,w),zh=n;Kb.ea("ready",g);Kb.ea("renderstart",g);Kb.ea("resize",g);var uq=a.Lm,hc=l.Ta,ic=(0,window.String)(l.Lf),vq=_.v;Kb.ea("renderstart",f);var tq=_.v;Kb.ea("ready",c);_.Q.L("widget-interactive-"+Kb.id,c);_.Q.L("widget-csi-tick-"+Kb.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.bg)("wdc",hc,ic,f):"wje0"===a||"wji_"===a?(0,_.bg)("wje0",hc,ic,f):"wje1"===a||"wji"===a?(0,_.bg)("wje1",hc,ic,f):"wh0"==a?((0,_.vf)(hc,ic).wh0=f||(0,_.Zf)(),(0,_.$f)("wh0",hc,ic)):"wh1"==a&&
((0,_.vf)(hc,ic).wh1=f||(0,_.Zf)(),(0,_.$f)("wh1",hc,ic))});h[5]=Kb;l.Jd&&l.Jd("e",h)};h=l;if(r=h.$o)for(a=0;a<r.length;a++)(new window.Image).src=r[a];var u={N:function(a,c,f){a=("string"===typeof a?window.document.getElementById(a):a)||_.q;c=c||{};c.callback=f||c.callback;a&&1===a.nodeType&&(0,_.Hg)(h,a,c,1);(0,_.Ig)(h)},go:function(a){if(a=("string"===typeof a?window.document.getElementById(a):a)||window.document.body){var c;c=h;for(var f=[],g=a.getElementsByTagName("iframe"),l={},n=0;n<g.length;++n){var r=
g[n].parentNode,u=r.id;if(u&&!l[u]){var w;a:{w=c;var V=r,oa=V.getAttribute("data-gwattr");if(oa!=_.t){for(var oa=oa.split(":"),Na={},ib=0;ib<oa.length;++ib){var Ea=oa[ib].split("="),Ah=window.decodeURIComponent(Ea[0]),Ea=window.decodeURIComponent(Ea[1]);Na[Ah]=Ea}if(Na[">type"]===w.Ta){V.removeAttribute("data-gwattr");w=Na;break a}}w=_.q}w&&(f.push({element:r,bg:w}),l[u]=1)}}c=f;for(f=0;f<c.length;++f)g=c[f],(0,_.Hg)(h,g.element,g.bg,3);c=h;f=[];a=a.getElementsByTagName("*");g=(0,window.RegExp)("(?:^|\\s)"+
c.oo+"(?:$|\\s)");for(l=0;l<a.length;++l)if(n=a[l],r=n.nodeName.toLowerCase(),!n.getAttribute("data-gapistub")&&(c.nh[r]||c.nh["*"])){u="";if(r!==c.al&&(u="data-",!g.test(n.className||n.getAttribute("class"))))continue;w=r={};V=c.ck;oa=n;Na=u;ib=_.q;for(ib in V)V.hasOwnProperty(ib)&&(w[ib]=oa.getAttribute(Na+ib));w=r;V=c.ja;oa=n;Na=_.q;for(Na in V)V.hasOwnProperty(Na)&&(w[Na]=oa.getAttribute(u+Na));f.push({element:n,bg:r})}c=f;for(f=0;f<c.length;++f)g=c[f],(0,_.Hg)(h,g.element,g.bg,0);(0,_.Ig)(h)}},
b:function(){_.Ma.WI=(0,_.ya)()}};if((r=(0,_.J)("lexps"))&&0<=_.ra.call(r,75))r=h.Ta,a=(0,_.qa)(_.Ma,"watt",(0,_.ya)()),(0,_.qa)(a,r,g),_.tg[h.Ta]=1,u.go=function(a){(0,_.sg)(a,h.Ta)},u.N=function(a,c){var f=c||{};f.type=h.Ta;var g=f,f=g.type;delete g.type;(0,_.Ca)(f&&_.tg[f],"Unsupported widget "+f);var l=("string"===typeof a?window.document.getElementById(a):a)||_.q;if(l&&1===l.nodeType){var n={},r;for(r in g)(0,_.Aa)(g,r)&&(n[r.toLowerCase()]=g[r]);g=n;g.rd=1;r=(0,_.lg)(f,l,0,g);(0,_.wg)(f,r)}}; r=h.Ta;a=(0,_.qa)(_.Ma,"sws",[]);if(!(0<=_.ra.call(a,r))){if("complete"!==_.Za.readyState)try{f()}catch(w){}(0,_.Dc)(f)}return u}};
_.Lg=_.Lg||{};_.A=_.Kg.prototype;_.A.xk=(0,_.ba)("b");_.A.Oi=function(a,c){c({})};_.A.show=function(){this.d.S().style.display="inline-block"};_.A.rj=function(){this.d.S().style.display="none"};_.A.close=function(){this.d.close({})};_.A.enable=(0,_.x)();_.A.disable=(0,_.x)();

}catch(e){_._DumpException(e)}
try{
_.up=(window.gapi||{}).load;
}catch(e){_._DumpException(e)}
try{
_.R.Ef("bubble",function(a){(0,_.up)("iframes-styles-bubble",a)});
}catch(e){_._DumpException(e)}
try{
_.R.Ef("slide-menu",function(a){(0,_.up)("iframes-styles-slide-menu",a)});
}catch(e){_._DumpException(e)}
try{

}catch(e){_._DumpException(e)}
try{
_.nx=function(a,c,f){a=(0,_.cg)(a);c=(0,_.hf)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.jf[c]["false"].height};if("bubble"!=a){if("none"==a)return _.jf[c]["false"];if("pp"==a)return _.ox}}return _.jf[c]["true"]};_.ox={width:180,height:35};_.px={"0":"plusone"};_.qx=(0,_.J)("iframes/plusone/preloadUrl");_.qx&&(_.px[8]=_.qx);(0,_.hg)(_.nf);_.px[1]=_.nf;
_.px[2]={width:[function(a,c){return c.annotation?(0,_.nx)(c.annotation,c.size,c).width:_.jf[(0,_.hf)(c.size)][(0,_.kf)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.nx)(c.annotation,c.size,c).height:_.jf[(0,_.hf)(c.size)][(0,_.kf)(c.count,c.size)].height}]};_.px[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.t}];_.px[4]=["div","button"];_.px[6]=["onstartinteraction","onendinteraction","onpopup"];_.gb=_.hb=_.Mg.ub(_.px);
(0,_.N)("gapi.plusone.render",_.hb.N);(0,_.N)("gapi.plusone.go",_.hb.go);(0,_.N)("googleapisv0.plusone.render",_.gb.N);(0,_.N)("googleapisv0.plusone.go",_.gb.go);
}catch(e){_._DumpException(e)}
});

// Copyright 2002-2012 Google Inc.
